// All user-facing copy, keyed by language. Strings may contain inline <em>/<code>
// markup; they are static and authored here, so rendering them as HTML is safe.

const en = {
  locale: "en-US",
  meta: {
    title: "History of Bitcoin",
    description: "The history of Bitcoin from the cypherpunk era to the fourth halving, plus the cryptography behind it: SHA-256, secp256k1, Schnorr, Merkle trees and proof-of-work. Try it live in your browser.",
  },
  skip: "Skip to content",
  pages: {
    history: {
      num: "01",
      title: "History",
      docTitle: "The story of Bitcoin, 1976–today",
      summary: "Three decades of cypherpunk research, the whitepaper, and every turning point since the genesis block.",
      includes: "Prologue · Timeline · Halving",
    },
    cryptography: {
      num: "02",
      title: "Cryptography",
      docTitle: "The cryptography behind Bitcoin",
      summary: "How SHA-256, elliptic curves and Merkle trees replace trust, plus a genesis block you can verify yourself.",
      includes: "7 primitives · Genesis block",
    },
    memecoins: {
      num: "03",
      title: "Memecoins",
      docTitle: "Memecoins: from Dogecoin to the DEX",
      summary: "From Dogecoin to pump.fun: how memecoins launch on a DEX long before a centralized exchange lists them.",
      includes: "Timeline · DEX to CEX · AMM simulator",
    },
    lab: {
      num: "04",
      title: "Lab",
      docTitle: "Bitcoin hash lab",
      summary: "Watch the avalanche effect and mine a block with real proof-of-work, right in your browser.",
      includes: "Avalanche · Mini miner",
    },
  },
  home: { chapters: "Four chapters", read: "Read" },
  next: { label: "Next chapter", home: "Back to the start" },
  sources: {
    heading: "Sources",
    desc: {
      whitepaper: "Satoshi Nakamoto, 31 October 2008",
      nakamoto: "Archive of emails, forum posts, and cypherpunk literature",
      core: "Bitcoin Core, the reference implementation since 2009",
      bips: "Bitcoin Improvement Proposals: SegWit, Taproot, BIP 32/39",
      secp: "Optimized C library for ECDSA &amp; Schnorr",
      bitcoinbook: "Mastering Bitcoin, Andreas M. Antonopoulos &amp; David A. Harding",
      bolts: "Lightning Network specifications",
      mempool: "Open-source block explorer &amp; visualizer",
      devdocs: "Protocol reference, block &amp; transaction formats",
      lmab: "Visual technical explanations, including the genesis block",
      fips: "Secure Hash Standard (SHA-256)",
      sec2: "Official secp256k1 curve parameters",
      dogecoin: "Dogecoin Core, the original memecoin's client",
      univ2: "Uniswap v2 core contracts: the constant-product AMM",
      uniwp: "Uniswap v2 whitepaper, Adams, Zinsmeister &amp; Robinson",
      raydium: "Raydium AMM program on Solana",
      spltoken: "SPL Token docs: mint and freeze authorities",
      shibburn: "CoinDesk: Vitalik burns $6.7B of SHIB (May 2021)",
      safemoon: "CoinDesk: SEC and DOJ charge SafeMoon executives (Nov 2023)",
      binancewif: "Binance listing announcement for WIF (Seed Tag)",
    },
  },
  nav: {
    home: "History of Bitcoin, back to top",
    brand: "History of Bitcoin",
    menu: "Menu",
    close: "Close",
    langLabel: "Language",
    links: [
      ["history", "History"],
      ["cryptography", "Cryptography"],
      ["memecoins", "Memecoins"],
      ["lab", "Lab"],
    ],
  },
  hero: {
    aria: "Intro",
    quoteTitle: "Message embedded in the coinbase of block #0",
    block: "Block #0",
    title: "Money written<br>in <em>mathematics</em>",
    lede: "From a cypherpunk mailing list to a trillion-dollar network. This is the story of Bitcoin, and the cryptography behind it that you can try right on this page.",
    since: "Since genesis",
    days: "days",
    supply: "Max supply",
    hash: "Hash",
    scroll: "SCROLL",
    scrollAria: "Scroll to live data",
  },
  prolog: {
    eyebrow: "Chapter 01 · History",
    title: "Before Satoshi, there were <em>cypherpunks</em>",
    lede: "Bitcoin did not appear out of nowhere. Nearly three decades of cryptographic research and failed attempts at digital money prepared every ingredient.",
    items: [
      ["1976", "Public-key cryptography", "\"New Directions in Cryptography\" introduced key exchange without a pre-shared secret, the foundation of digital signatures.", "Whitfield Diffie & Martin Hellman"],
      ["1982", "Blind signatures &amp; eCash", "Chaum designed untraceable payments. DigiCash (1989) turned the idea into a product, but it still depended on a single central server.", "David Chaum"],
      ["1985", "Elliptic curve cryptography", "Proposed independently by two researchers. ECC offers security comparable to RSA with much shorter keys.", "Neal Koblitz & Victor Miller"],
      ["1991", "Timestamped hash chains", "Documents are timestamped and linked by hashes so their history cannot be altered. This work is cited three times in the Bitcoin whitepaper.", "Stuart Haber & W. Scott Stornetta"],
      ["1992", "The Cypherpunks mailing list", "A community that believed privacy must be defended with code. \"A Cypherpunk's Manifesto\" followed the next year.", "Eric Hughes, Timothy May, John Gilmore"],
      ["1997", "Hashcash", "Proof-of-work to fight email spam. Satoshi used the same mechanism to secure the blockchain.", "Adam Back"],
      ["1998", "b-money", "A proposal for distributed money with a shared ledger and money created through computation. Cited directly in the whitepaper.", "Wei Dai"],
      ["2004 – 2005", "RPOW &amp; Bit Gold", "Reusable proof-of-work tokens, and hash-chained \"digital gold\". Both came close to solving the double-spend problem.", "Hal Finney · Nick Szabo"],
    ],
  },
  quote: {
    text: "\"A purely peer-to-peer version of electronic cash would allow online payments to be sent directly from one party to another without going through a financial institution.\"",
    cite: "Satoshi Nakamoto · Bitcoin Whitepaper, 2008",
  },
  timeline: {
    eyebrow: "Timeline · 2008–today",
    title: "The <em>Bitcoin</em> timeline",
    lede: "The moments that shaped the network: from a nine-page PDF to ETFs on Wall Street.",
    showAll: (n) => `Show all ${n} moments`,
    showKey: "Show key moments only",
    // [date, tag, hot, title, text]
    items: [
      ["18 Aug 2008", "bitcoin.org", false, "bitcoin.org is registered", "Two months before the whitepaper circulated, the stage was set anonymously."],
      ["31 Oct 2008", "Whitepaper", true, "\"Bitcoin: A Peer-to-Peer Electronic Cash System\"", "Satoshi Nakamoto posts a nine-page paper to the cryptography mailing list. It solves the double-spend problem without a trusted third party, using proof-of-work and a chain of blocks."],
      ["3 Jan 2009", "Block #0", true, "The genesis block is mined", "Its 50 BTC reward can never be spent. The Times headline in its coinbase serves as both a timestamp and a statement."],
      ["9 Jan 2009", "v0.1", false, "Bitcoin v0.1 is released", "The first open-source software, for Windows. Anyone can run a node and mine."],
      ["12 Jan 2009", "Block #170", false, "First transaction: Satoshi → Hal Finney", "10 BTC changes hands. Finney, creator of RPOW, is the first person besides Satoshi to run a node."],
      ["5 Oct 2009", "", false, "First price: US$1 = 1,309.03 BTC", "New Liberty Standard derives an exchange rate from the electricity cost of mining one bitcoin."],
      ["22 May 2010", "Pizza Day", true, "10,000 BTC for two pizzas", "Laszlo Hanyecz makes the first documented purchase of real goods with bitcoin. The date is still celebrated every year."],
      ["15 Aug 2010", "Block #74,638", false, "The value overflow incident", "An integer overflow bug creates 184 billion BTC. Within hours a patch is released and the chain is forked back. It remains the only major inflation bug ever exploited."],
      ["Dec 2010 – Apr 2011", "", false, "Satoshi disappears", "The last forum post is on 12 December 2010. Control of the project passes to Gavin Andresen, and Satoshi is never heard from again."],
      ["28 Nov 2012", "Halving 1", false, "Block reward drops 50 → 25 BTC", "Monetary policy written in code executes exactly on schedule at block 210,000."],
      ["Feb 2014", "", false, "The collapse of Mt. Gox", "The exchange that once handled most of the world's volume loses around 850,000 BTC. A lesson repeated ever since: <em>not your keys, not your coins</em>."],
      ["9 Jul 2016", "Halving 2", false, "Block reward drops to 12.5 BTC", "Block 420,000. The network matures and the scaling debate heats up."],
      ["24 Aug 2017", "SegWit", true, "Segregated Witness activates", "A soft fork at block 481,824 fixes transaction malleability and paves the way for Lightning. Three weeks earlier, the big-block camp split off as Bitcoin Cash."],
      ["Mar 2018", "Layer 2", false, "Lightning Network goes live on mainnet", "Off-chain payment channels for instant, cheap transactions, still secured by the Bitcoin blockchain."],
      ["11 May 2020", "Halving 3", false, "Block reward drops to 6.25 BTC", "It happens amid a pandemic and massive monetary stimulus. The \"digital gold\" narrative grows stronger."],
      ["7 Sep 2021", "", false, "El Salvador makes it legal tender", "The first country to adopt bitcoin as official currency alongside the US dollar."],
      ["14 Nov 2021", "Taproot", true, "Taproot &amp; Schnorr signatures", "The biggest upgrade since SegWit, active at block 709,632. BIPs 340–342 bring aggregatable signatures and more private scripts."],
      ["10 Jan 2024", "ETF", false, "SEC approves spot bitcoin ETFs", "Eleven products begin trading the next day. Bitcoin officially enters mainstream institutional portfolios."],
      ["20 Apr 2024", "Halving 4", false, "Block reward drops to 3.125 BTC", "Block 840,000. More than 93% of all 21 million BTC have been mined."],
      ["± 2140", "Last satoshi", false, "The last bitcoin is mined", "After 33 halvings, the block subsidy reaches zero. Miners are paid by transaction fees alone."],
    ],
  },
  crypto: {
    eyebrow: "Chapter 02 · Cryptography",
    title: "Trust, replaced by <em>cryptography</em>",
    lede: "Bitcoin invented no new algorithms. It assembled primitives tested over decades into a system that needs no central authority.",
    curveAria: "Plot of the elliptic curve y² = x³ + 7 over the real numbers",
    merkleAria: "Merkle tree diagram with four transactions",
    cards: {
      hash: {
        kicker: "01 · Hash function",
        title: "SHA-256, applied twice",
        body: [
          "Everything in Bitcoin is identified by a hash: blocks, transactions, even addresses. SHA-256 is deterministic and one-way. Flip one input bit and on average half the output bits change (the <em>avalanche effect</em>).",
          "Bitcoin uses <code>SHA256(SHA256(x))</code> for block and transaction IDs, as a defense against length-extension attacks.",
        ],
        spec: "FIPS 180-4 · 256-bit output · 64 compression rounds · NSA/NIST 2001",
      },
      pow: {
        kicker: "02 · Proof-of-Work",
        title: "A lottery that cannot be rigged",
        body: [
          "Miners vary the <code>nonce</code> until the block header hash falls below a target. The only way is to keep trying, so rewriting history costs more energy than the entire network.",
          "The target adjusts every 2,016 blocks so that one block is found roughly every 10 minutes.",
        ],
        spec: "hash(header) &lt; target · retarget every 2016 blocks",
      },
      ecdsa: {
        kicker: "03 · Digital signatures",
        title: "ECDSA on the secp256k1 curve",
        body: ["A private key is a random 256-bit number <code>k</code>. The public key <code>K = k·G</code> is easy to compute, but reversing it (the discrete logarithm problem) is practically impossible."],
        spec: "y² = x³ + 7 (mod p) · p = 2²⁵⁶ − 2³² − 977 · SEC 2",
      },
      merkle: {
        kicker: "04 · Data structure",
        title: "Merkle tree",
        body: ["Thousands of transactions are summarized into a single 32-byte hash in the header. Light (SPV) wallets only need a <em>Merkle proof</em> of length log₂(n) to prove a transaction is in a block."],
        spec: "Merkle 1979 · whitepaper §7–8",
      },
      schnorr: {
        kicker: "05 · Taproot",
        title: "Schnorr signatures",
        body: ["Linear, aggregatable signatures: a multisig transaction looks just like a regular one. Smaller, more private, and provably secure."],
        spec: "BIP 340 · 64 bytes · active Nov 2021",
      },
      address: {
        kicker: "06 · Addresses",
        title: "HASH160 &amp; Bech32",
        body: ["The public key is hashed with <code>RIPEMD160(SHA256(K))</code> and then encoded. Base58Check avoids look-alike characters (0/O, l/I); Bech32 adds BCH error detection."],
        spec: "1… legacy · 3… P2SH · bc1q… SegWit · bc1p… Taproot",
      },
      wallet: {
        kicker: "07 · Wallets",
        title: "HD wallets &amp; seed phrases",
        body: ["A single 12–24 word seed (BIP 39) derives an unlimited tree of keys via HMAC-SHA512 (BIP 32). Back up once, recover everything."],
        spec: "BIP 32 · BIP 39 · BIP 44/84/86",
      },
    },
  },
  lab: {
    eyebrow: "Chapter 04 · Lab",
    title: "The <em>hash</em> lab",
    lede: "Everything is computed locally in your browser with a pure JavaScript SHA-256 implementation. No data is sent anywhere.",
    avalanche: "Avalanche effect",
    input: "INPUT",
    output: "OUTPUT · 64 HEX",
    defaultInput: "Satoshi Nakamoto",
    changeOne: "Change a single letter",
    bitsChanged: (n) => `${n}/256 bits changed`,
    avalancheNote: "Try changing \"Satoshi\" to \"satoshi\". On average, close to 50% of the bits change.",
    miner: "Mini miner",
    blockData: "BLOCK DATA",
    defaultBlock: "Block #1 · Alice → Bob · 1 BTC",
    zeros: "LEADING ZEROS",
    difficulty: "Difficulty",
    nonce: "Nonce",
    rate: "Hashes/sec",
    time: "Time",
    start: "Start mining",
    stop: "Stop",
    notes: {
      idle: () => "Each extra hex zero = 16× harder.",
      avg: (n) => `${n} attempts on average.`,
      searching: () => "Searching for a nonce…",
      stopped: () => "Stopped.",
      found: (n) => `Block found after ${n} attempts.`,
    },
  },
  genesis: {
    eyebrow: "Proof · Block #0",
    title: "Verify the <em>genesis block</em>",
    lede: "A block header is only 80 bytes. Hash it twice, reverse the byte order, and you get exactly the same hash Satoshi computed on 3 January 2009.",
    rows: ["Version", "Previous block", "Merkle root", "Time", "Bits (target)", "Nonce"],
    raw: "Raw header · 80 bytes",
    legend: ["version", "prev hash", "merkle root", "time", "bits", "nonce"],
    button: "Compute SHA256²",
    idle: "Press the button to compute the hash in your browser.",
    reversed: "SHA256(SHA256(header)), reversed:",
    ok: "✓ Matches the genesis block hash. Note the 10 leading zeros: that is the proof of work.",
    fail: "✗ No match.",
  },
  halving: {
    eyebrow: "Halving · Monetary policy",
    title: "<em>Programmed</em> scarcity",
    lede: "Every 210,000 blocks (about four years), the miner reward is cut in half. The result is a geometric series that converges just below 21 million BTC.",
    reward: "Block reward (BTC)",
    supply: "Total supply (million BTC)",
    chartAria: "Chart of block reward and total supply per halving epoch",
    hint: "Hover or tap a bar for details.",
    estimated: "estimated",
    block: "block",
    tip: (e, nf) => `<b>${e.year}${e.future ? " (estimated)" : ""}</b> · block ${nf(e.block)} · reward <b>${nf(e.reward, 5)} BTC</b> · supply when it began <b>${nf(e.supplyStart, 2)} million</b>`,
  },
  memeTimeline: {
    eyebrow: "Chapter 03 · Memecoins",
    title: "From a joke to a <em>launchpad</em>",
    lede: "How memecoins went from a Shiba Inu fork to tokens that trade on a DEX within seconds of creation, often long before any centralized exchange lists them.",
    showAll: (n) => `Show all ${n} moments`,
    showKey: "Show key moments only",
    items: [
      ["6 Dec 2013", "Scrypt", true, "Dogecoin: the first memecoin", "Billy Markus and Jackson Palmer put the Shiba Inu \"doge\" meme on Litecoin-derived code. Built as a joke, it has a real community within weeks."],
      ["Jan 2014", "", false, "Doge sends a bobsled team to Sochi", "The community raises tens of thousands of dollars in DOGE so the Jamaican bobsled team can compete at the Winter Olympics. A meme proves it can move people."],
      ["2 Nov 2018", "Uniswap v1", true, "Anyone can list a token", "Uniswap launches on Ethereum with the x·y=k automated market maker. No order book and no listing approval: create a pool and the token is tradable. Every later memecoin launch builds on this."],
      ["May 2020", "Uniswap v2", false, "Direct token pairs", "Any two ERC-20 tokens can now pair directly. Burning or locking the LP tokens becomes the standard \"liquidity locked\" promise."],
      ["Aug 2020", "SHIB", true, "Shiba Inu, the \"Dogecoin killer\"", "An anonymous creator, \"Ryoshi\", launches SHIB straight into a Uniswap pool and sends half the supply to Vitalik Buterin. No exchange, no presale: just a pool."],
      ["Sep 2020", "BSC", false, "PancakeSwap and cheap gas", "BNB Smart Chain and PancakeSwap offer the same model at a fraction of Ethereum's fees, opening the door to thousands of low-cost launches."],
      ["Mar 2021", "", false, "SafeMoon and reflection tokens", "SafeMoon launches on PancakeSwap with a 10% transaction tax paid partly to holders. In November 2023 US prosecutors charge its executives with fraud."],
      ["8 May 2021", "DOGE", true, "Dogecoin peaks on SNL night", "Pushed largely by Elon Musk's posts, DOGE reaches about $0.73 on the day he hosts Saturday Night Live."],
      ["10 May 2021", "Binance", true, "SHIB reaches Binance", "Nine months after its Uniswap pool, SHIB lists on Binance. Days later Vitalik burns about 410 trillion SHIB (≈ $6.7 billion), after giving 50 trillion to an Indian COVID-19 relief fund."],
      ["Oct – Nov 2021", "Honeypot", false, "The Squid Game token", "SQUID rides the Netflix hype on BSC, but its contract stops most holders from selling. On 1 November the developers cash out and the price collapses to almost zero."],
      ["25 Dec 2022", "Solana", true, "The BONK airdrop", "With Solana in a slump after FTX collapses, half of BONK's supply is airdropped to the Solana community. It becomes the chain's first breakout memecoin."],
      ["15 Apr 2023", "PEPE", true, "PEPE: 20 days from Uniswap to Binance", "No tax, no presale, just a Uniswap pool. Binance lists it on 5 May and its market cap passes $1 billion."],
      ["15 Dec 2023", "Binance", false, "BONK lists on Binance", "Almost a year after the airdrop, BONK reaches Binance with the high-risk Seed Tag."],
      ["19 Jan 2024", "pump.fun", true, "pump.fun: launch in one click", "Anyone can create a Solana token for a few cents. It trades on a bonding curve and, at about $69,000 market cap, \"graduates\" to a Raydium pool."],
      ["5 Mar 2024", "WIF", false, "dogwifhat reaches Binance", "Launched on Solana DEXs in November 2023, the dog in a pink beanie lists on Binance about three and a half months later."],
      ["16 Mar 2024", "BOME", false, "BOOK OF MEME in two days", "BOME goes from its Solana launch to a Binance listing in about two days, the fastest DEX-to-CEX run of the cycle."],
      ["11 Nov 2024", "AI memes", false, "Binance lists ACT and PNUT", "ACT, created on pump.fun, and PNUT multiply in price on the announcement. Tier-1 exchanges now pick up launchpad tokens within weeks."],
      ["17 Jan 2025", "TRUMP", true, "The official TRUMP coin", "Launched on Solana three days before the inauguration, it passes $13 billion in market cap in under two days, then gives back most of it."],
      ["14 Feb 2025", "LIBRA", false, "The LIBRA scandal", "A token promoted by Argentina's president Javier Milei falls more than 90% within hours as early wallets sell."],
      ["20 Mar 2025", "PumpSwap", false, "pump.fun builds its own DEX", "Graduated tokens now move to PumpSwap instead of Raydium, instantly and without the migration fee, with trading fees shared with creators."],
    ],
  },
  memes: {
    lifecycle: {
      eyebrow: "Before the CEX",
      title: "From <em>DEX</em> to Binance",
      lede: "Almost every memecoin since 2020 starts on a decentralized exchange. These are the stages it passes through before a centralized exchange, if it ever gets there.",
      steps: [
        ["Create", "A contract is deployed, or a launchpad mints the token with a fixed supply (1 billion on pump.fun). It costs cents on Solana and more on Ethereum."],
        ["Bonding curve", "On a launchpad, every buy raises the price along a preset curve. When the curve fills (about $69K on pump.fun), the token graduates."],
        ["DEX pool", "Liquidity moves into an AMM pool on PumpSwap, Raydium or Uniswap. The x·y=k formula sets the price, and the LP tokens are burned or locked."],
        ["Snipers &amp; bots", "Bots buy in the very first blocks, then Telegram trading bots and copy-traders pile in. Who holds early decides who can sell to whom."],
        ["Trending", "Volume puts it on DEX Screener and DEXTools trending lists, then on X and Telegram. Smaller centralized exchanges often list it first."],
        ["Tier-1 CEX", "Binance, OKX or Coinbase. Binance usually lists memecoins with a Seed Tag that marks them as high-risk, and perpetual futures often follow."],
      ],
    },
    race: {
      eyebrow: "Time to Binance",
      title: "How long the <em>DEX</em> phase lasted",
      lede: "From the first DEX trade (or airdrop) to a Binance spot listing. Log scale, because the fastest took two days and the slowest almost a year.",
      scale: "log scale · days",
      // [token, chain, from, to, days, label]
      rows: [
        ["BOME", "Solana", "14 Mar 2024", "16 Mar 2024", 2, "2 days"],
        ["PEPE", "Ethereum", "15 Apr 2023", "5 May 2023", 20, "20 days"],
        ["WIF", "Solana", "Nov 2023", "5 Mar 2024", 106, "≈ 3.5 months"],
        ["SHIB", "Ethereum", "Aug 2020", "10 May 2021", 275, "≈ 9 months"],
        ["BONK", "Solana", "25 Dec 2022", "15 Dec 2023", 355, "≈ 1 year"],
      ],
    },
    amm: {
      eyebrow: "Try it",
      title: "Why the price <em>jumps</em>",
      lede: "A DEX pool has no order book. It holds two reserves and keeps their product constant, so every buy makes the next token more expensive. The smaller the pool, the bigger the jump.",
      panel: "Constant-product pool",
      pool: "Pool",
      buy: "You buy with",
      receive: "You receive",
      avg: "Average price",
      impact: "Price impact",
      after: "Price after",
      note: "x·y = k with a 0.25% fee, like Raydium's standard AMM. Prices in SOL per million MEME.",
      reserveSol: "SOL in pool",
      reserveMeme: "MEME in pool",
    },
    checklist: {
      eyebrow: "Before you buy",
      title: "A DEX <em>safety</em> checklist",
      lede: "Most memecoin losses come from a handful of contract and liquidity tricks. Each of these can be checked on-chain in minutes.",
      items: [
        ["Liquidity burned or locked", "If the deployer still holds the LP tokens, they can pull the pool and leave holders with nothing: a rug pull."],
        ["Mint authority revoked", "On Solana the mint authority should be null; on EVM chains ownership should be renounced or there should be no mint function. Otherwise new supply can be printed."],
        ["Freeze authority disabled", "A Solana token with a freeze authority can have your token account frozen so you cannot sell."],
        ["You can actually sell", "Honeypot contracts allow buys but block sells, as the Squid Game token did. Simulate a sell before you buy."],
        ["Taxes and holder spread", "Check buy and sell taxes and how much the top 10 wallets hold. A few wallets owning most of the supply can crash the price at will."],
        ["Verified, non-upgradeable contract", "Unverified or proxy contracts can change their behavior after you buy."],
      ],
    },
  },
  live: {
    eyebrow: "Live · on-chain",
    title: "Bitcoin <em>right now</em>",
    lede: "The network today, shown the way Satoshi's own Bitcoin v0.1 client looked in January 2009. Refreshed every 30 seconds.",
    latestBlock: "Latest block:",
    price: "Price:",
    halving: "Next halving:",
    network: "Network:",
    halvingValue: (n, date, now, next) => `${n} blocks · ≈ ${date} · reward ${now} → ${next} BTC`,
    networkValue: (mined, pct, diff, left) => `${mined}M BTC mined (${pct}) · difficulty ${diff} in ${left} blocks`,
    change: "24h",
    tab: "Latest Blocks",
    cols: ["Status", "Date", "Description", "Debit", "Credit"],
    depth: (n) => (n === 1 ? "1 block" : `${n} blocks`),
    desc: (pool, tx, mb) => `Mined by ${pool} · ${tx} tx · ${mb} MB`,
    unknownPool: "unknown pool",
    connecting: "Connecting...",
    updated: (ago) => `Updated ${ago}`,
    partial: "Partly offline, retrying",
    error: "Offline",
    retry: "Retry",
    fee: (n) => `${n} sat/vB`,
    blocks: (n) => `${n} blocks`,
  },
};

const id = {
  locale: "id-ID",
  meta: {
    title: "Sejarah Bitcoin",
    description: "Sejarah Bitcoin dari era cypherpunk hingga halving keempat, plus kriptografi di baliknya: SHA-256, secp256k1, Schnorr, Merkle tree dan proof-of-work. Bisa dicoba langsung di browser.",
  },
  skip: "Lompat ke konten",
  pages: {
    history: {
      num: "01",
      title: "Sejarah",
      docTitle: "Kisah Bitcoin, 1976–sekarang",
      summary: "Tiga dekade riset cypherpunk, whitepaper, dan setiap titik balik sejak blok genesis.",
      includes: "Prolog · Lini masa · Halving",
    },
    cryptography: {
      num: "02",
      title: "Kriptografi",
      docTitle: "Kriptografi di balik Bitcoin",
      summary: "Cara SHA-256, kurva eliptik, dan Merkle tree menggantikan kepercayaan, plus blok genesis yang bisa kamu verifikasi sendiri.",
      includes: "7 primitif · Blok genesis",
    },
    memecoins: {
      num: "03",
      title: "Memecoin",
      docTitle: "Memecoin: dari Dogecoin sampai DEX",
      summary: "Dari Dogecoin sampai pump.fun: bagaimana memecoin meluncur di DEX jauh sebelum bursa terpusat me-listing-nya.",
      includes: "Lini masa · DEX ke CEX · Simulator AMM",
    },
    lab: {
      num: "04",
      title: "Lab",
      docTitle: "Lab hash Bitcoin",
      summary: "Lihat avalanche effect dan tambang blok dengan proof-of-work sungguhan, langsung di browser.",
      includes: "Avalanche · Mini penambang",
    },
  },
  home: { chapters: "Empat bab", read: "Baca" },
  next: { label: "Bab berikutnya", home: "Kembali ke awal" },
  sources: {
    heading: "Sumber",
    desc: {
      whitepaper: "Satoshi Nakamoto, 31 Oktober 2008",
      nakamoto: "Arsip email, postingan forum, dan literatur cypherpunk",
      core: "Bitcoin Core, implementasi referensi sejak 2009",
      bips: "Bitcoin Improvement Proposals: SegWit, Taproot, BIP 32/39",
      secp: "Pustaka C teroptimasi untuk ECDSA &amp; Schnorr",
      bitcoinbook: "Mastering Bitcoin, Andreas M. Antonopoulos &amp; David A. Harding",
      bolts: "Spesifikasi Lightning Network",
      mempool: "Explorer &amp; visualisasi blok open source",
      devdocs: "Referensi protokol, format blok &amp; transaksi",
      lmab: "Penjelasan teknis visual, termasuk blok genesis",
      fips: "Secure Hash Standard (SHA-256)",
      sec2: "Parameter resmi kurva secp256k1",
      dogecoin: "Dogecoin Core, klien memecoin pertama",
      univ2: "Kontrak inti Uniswap v2: AMM constant-product",
      uniwp: "Whitepaper Uniswap v2, Adams, Zinsmeister &amp; Robinson",
      raydium: "Program AMM Raydium di Solana",
      spltoken: "Dokumentasi SPL Token: mint dan freeze authority",
      shibburn: "CoinDesk: Vitalik membakar SHIB senilai US$6,7 miliar (Mei 2021)",
      safemoon: "CoinDesk: SEC dan DOJ mendakwa eksekutif SafeMoon (Nov 2023)",
      binancewif: "Pengumuman listing WIF di Binance (Seed Tag)",
    },
  },
  nav: {
    home: "Sejarah Bitcoin, ke atas",
    brand: "Sejarah Bitcoin",
    menu: "Menu",
    close: "Tutup",
    langLabel: "Bahasa",
    links: [
      ["history", "Sejarah"],
      ["cryptography", "Kriptografi"],
      ["memecoins", "Memecoin"],
      ["lab", "Lab"],
    ],
  },
  hero: {
    aria: "Pembuka",
    quoteTitle: "Pesan yang tertanam di coinbase blok #0",
    block: "Blok #0",
    title: "Uang yang ditulis<br>dengan <em>matematika</em>",
    lede: "Dari milis cypherpunk hingga jaringan bernilai triliunan dolar. Ini kisah Bitcoin, dan kriptografi di baliknya yang bisa kamu coba langsung di halaman ini.",
    since: "Sejak genesis",
    days: "hari",
    supply: "Pasokan maks",
    hash: "Hash",
    scroll: "GULIR",
    scrollAria: "Gulir ke data live",
  },
  prolog: {
    eyebrow: "Bab 01 · Sejarah",
    title: "Sebelum Satoshi, ada <em>cypherpunk</em>",
    lede: "Bitcoin tidak muncul tiba-tiba. Hampir tiga dekade riset kriptografi dan upaya uang digital yang gagal menyiapkan semua bahannya.",
    items: [
      ["1976", "Kriptografi kunci publik", "Makalah \"New Directions in Cryptography\" memperkenalkan pertukaran kunci tanpa rahasia bersama, fondasi tanda tangan digital.", "Whitfield Diffie & Martin Hellman"],
      ["1982", "Blind signatures &amp; eCash", "Chaum merancang pembayaran yang tidak bisa dilacak. Lewat DigiCash (1989) idenya jadi produk, tapi masih bergantung pada satu server pusat.", "David Chaum"],
      ["1985", "Kriptografi kurva eliptik", "Diusulkan secara terpisah oleh dua peneliti. ECC menawarkan keamanan setara RSA dengan kunci yang jauh lebih pendek.", "Neal Koblitz & Victor Miller"],
      ["1991", "Rantai hash bertanda waktu", "Dokumen diberi stempel waktu dan dirangkai dengan hash sehingga riwayatnya tidak bisa diubah. Makalah ini dikutip tiga kali di whitepaper Bitcoin.", "Stuart Haber & W. Scott Stornetta"],
      ["1992", "Milis Cypherpunks", "Komunitas yang percaya privasi harus dijaga dengan kode. \"A Cypherpunk's Manifesto\" terbit tahun berikutnya.", "Eric Hughes, Timothy May, John Gilmore"],
      ["1997", "Hashcash", "Proof-of-work untuk melawan spam email. Satoshi memakai mekanisme yang sama untuk mengamankan blockchain.", "Adam Back"],
      ["1998", "b-money", "Usulan uang terdistribusi dengan buku besar bersama dan pembuatan uang lewat komputasi. Dikutip langsung di whitepaper.", "Wei Dai"],
      ["2004 – 2005", "RPOW &amp; Bit Gold", "Token proof-of-work yang bisa dipakai ulang, dan \"emas digital\" berantai hash. Keduanya hampir menyelesaikan masalah double-spend.", "Hal Finney · Nick Szabo"],
    ],
  },
  quote: en.quote,
  timeline: {
    eyebrow: "Lini masa · 2008–sekarang",
    title: "Lini masa <em>Bitcoin</em>",
    lede: "Momen yang membentuk jaringan: dari sembilan halaman PDF sampai ETF di Wall Street.",
    showAll: (n) => `Tampilkan semua ${n} momen`,
    showKey: "Tampilkan momen kunci saja",
    items: [
      ["18 Agu 2008", "bitcoin.org", false, "Domain bitcoin.org didaftarkan", "Dua bulan sebelum whitepaper beredar, panggungnya sudah disiapkan secara anonim."],
      ["31 Okt 2008", "Whitepaper", true, "\"Bitcoin: A Peer-to-Peer Electronic Cash System\"", "Satoshi Nakamoto mengirim makalah sembilan halaman ke milis kriptografi. Isinya menjawab masalah double-spend tanpa pihak ketiga, dengan proof-of-work dan rantai blok."],
      ["3 Jan 2009", "Blok #0", true, "Blok genesis ditambang", "Imbalan 50 BTC yang tidak akan pernah bisa dibelanjakan. Judul koran The Times di coinbase-nya jadi stempel waktu sekaligus pernyataan sikap."],
      ["9 Jan 2009", "v0.1", false, "Bitcoin v0.1 dirilis", "Perangkat lunak open source pertama untuk Windows. Siapa pun bisa menjalankan node dan menambang."],
      ["12 Jan 2009", "Blok #170", false, "Transaksi pertama: Satoshi → Hal Finney", "10 BTC berpindah tangan. Finney, yang sebelumnya membuat RPOW, menjadi orang pertama selain Satoshi yang menjalankan node."],
      ["5 Okt 2009", "", false, "Harga pertama: US$1 = 1.309,03 BTC", "New Liberty Standard menghitung kurs dari biaya listrik untuk menambang satu bitcoin."],
      ["22 Mei 2010", "Pizza Day", true, "10.000 BTC untuk dua pizza", "Laszlo Hanyecz melakukan pembelian barang nyata pertama yang terdokumentasi dengan bitcoin. Tanggal ini masih dirayakan tiap tahun."],
      ["15 Agu 2010", "Blok #74.638", false, "Insiden value overflow", "Bug integer overflow menciptakan 184 miliar BTC. Dalam beberapa jam patch dirilis dan rantai di-fork kembali. Ini satu-satunya bug inflasi besar yang pernah dieksploitasi."],
      ["Des 2010 – Apr 2011", "", false, "Satoshi menghilang", "Postingan forum terakhir pada 12 Desember 2010. Kendali proyek diserahkan ke Gavin Andresen, lalu Satoshi tidak pernah muncul lagi."],
      ["28 Nov 2012", "Halving 1", false, "Imbalan blok turun 50 → 25 BTC", "Kebijakan moneter yang tertulis di kode berjalan persis sesuai jadwal di blok 210.000."],
      ["Feb 2014", "", false, "Runtuhnya Mt. Gox", "Bursa yang pernah memproses sebagian besar volume dunia kehilangan sekitar 850.000 BTC. Pelajaran yang terus diulang: <em>not your keys, not your coins</em>."],
      ["9 Jul 2016", "Halving 2", false, "Imbalan blok turun ke 12,5 BTC", "Blok 420.000. Jaringan makin matang dan perdebatan soal skalabilitas memanas."],
      ["24 Agu 2017", "SegWit", true, "Segregated Witness aktif", "Soft fork di blok 481.824 memperbaiki malleability transaksi dan membuka jalan bagi Lightning. Tiga minggu sebelumnya, kubu blok besar memisahkan diri sebagai Bitcoin Cash."],
      ["Mar 2018", "Layer 2", false, "Lightning Network di mainnet", "Kanal pembayaran off-chain untuk transaksi instan dan murah, tetap dijamin oleh blockchain Bitcoin."],
      ["11 Mei 2020", "Halving 3", false, "Imbalan blok turun ke 6,25 BTC", "Terjadi di tengah pandemi dan stimulus moneter besar-besaran. Narasi \"emas digital\" makin menguat."],
      ["7 Sep 2021", "", false, "El Salvador: alat pembayaran sah", "Negara pertama yang menjadikan bitcoin mata uang resmi di samping dolar AS."],
      ["14 Nov 2021", "Taproot", true, "Taproot &amp; tanda tangan Schnorr", "Upgrade terbesar sejak SegWit, aktif di blok 709.632. BIP 340–342 membawa tanda tangan yang bisa diagregasi dan skrip yang lebih privat."],
      ["10 Jan 2024", "ETF", false, "SEC menyetujui ETF bitcoin spot", "Sebelas produk mulai diperdagangkan keesokan harinya. Bitcoin resmi masuk portofolio institusi arus utama."],
      ["20 Apr 2024", "Halving 4", false, "Imbalan blok turun ke 3,125 BTC", "Blok 840.000. Lebih dari 93% dari 21 juta BTC sudah ditambang."],
      ["± 2140", "Satoshi terakhir", false, "Bitcoin terakhir ditambang", "Setelah 33 halving, imbalan blok menjadi nol. Penambang hanya dibayar dari biaya transaksi."],
    ],
  },
  crypto: {
    eyebrow: "Bab 02 · Kriptografi",
    title: "Kepercayaan diganti <em>kriptografi</em>",
    lede: "Bitcoin tidak menciptakan algoritma baru. Ia merangkai primitif yang sudah teruji puluhan tahun menjadi sistem yang tidak membutuhkan otoritas pusat.",
    curveAria: "Grafik kurva eliptik y² = x³ + 7 di bilangan real",
    merkleAria: "Diagram Merkle tree dengan empat transaksi",
    cards: {
      hash: {
        kicker: "01 · Fungsi hash",
        title: "SHA-256, dijalankan dua kali",
        body: [
          "Semua hal di Bitcoin diidentifikasi dengan hash: blok, transaksi, sampai alamat. SHA-256 bersifat deterministik dan satu arah. Ubah satu bit input, dan rata-rata separuh bit output ikut berubah (<em>avalanche effect</em>).",
          "Bitcoin memakai <code>SHA256(SHA256(x))</code> untuk ID blok dan transaksi, sebagai pertahanan terhadap serangan length-extension.",
        ],
        spec: "FIPS 180-4 · output 256 bit · 64 ronde kompresi · NSA/NIST 2001",
      },
      pow: {
        kicker: "02 · Proof-of-Work",
        title: "Lotere yang tidak bisa dicurangi",
        body: [
          "Penambang mengganti <code>nonce</code> sampai hash header blok berada di bawah target. Satu-satunya cara adalah mencoba, sehingga menulis ulang sejarah butuh energi lebih besar dari seluruh jaringan.",
          "Target disesuaikan tiap 2.016 blok agar rata-rata satu blok lahir setiap ~10 menit.",
        ],
        spec: "hash(header) &lt; target · retarget 2016 blok",
      },
      ecdsa: {
        kicker: "03 · Tanda tangan digital",
        title: "ECDSA di kurva secp256k1",
        body: ["Kunci privat adalah angka acak 256 bit <code>k</code>. Kunci publik <code>K = k·G</code> mudah dihitung, tetapi membalikkannya (masalah logaritma diskret) mustahil secara praktis."],
        spec: en.crypto.cards.ecdsa.spec,
      },
      merkle: {
        kicker: "04 · Struktur data",
        title: "Merkle tree",
        body: ["Ribuan transaksi diringkas menjadi satu hash 32 byte di header. Dompet ringan (SPV) cukup meminta <em>Merkle proof</em> sepanjang log₂(n) untuk membuktikan sebuah transaksi ada di blok."],
        spec: en.crypto.cards.merkle.spec,
      },
      schnorr: {
        kicker: "05 · Taproot",
        title: "Schnorr signatures",
        body: ["Tanda tangan linear yang bisa diagregasi: transaksi multisig terlihat sama seperti transaksi biasa. Lebih ringkas, lebih privat, dan terbukti aman secara formal."],
        spec: "BIP 340 · 64 byte · aktif Nov 2021",
      },
      address: {
        kicker: "06 · Alamat",
        title: "HASH160 &amp; Bech32",
        body: ["Kunci publik di-hash dengan <code>RIPEMD160(SHA256(K))</code> lalu dikodekan. Base58Check menghindari karakter mirip (0/O, l/I); Bech32 menambah deteksi kesalahan BCH."],
        spec: en.crypto.cards.address.spec,
      },
      wallet: {
        kicker: "07 · Dompet",
        title: "HD wallet &amp; seed phrase",
        body: ["Satu seed 12–24 kata (BIP 39) menurunkan pohon kunci tak terbatas lewat HMAC-SHA512 (BIP 32). Cadangkan sekali, pulihkan semuanya."],
        spec: en.crypto.cards.wallet.spec,
      },
    },
  },
  lab: {
    eyebrow: "Bab 04 · Lab",
    title: "Laboratorium <em>hash</em>",
    lede: "Semua dihitung lokal di browser kamu dengan implementasi SHA-256 murni JavaScript. Tidak ada data yang dikirim ke mana pun.",
    avalanche: "Avalanche effect",
    input: "INPUT",
    output: "OUTPUT · 64 HEX",
    defaultInput: "Satoshi Nakamoto",
    changeOne: "Ubah satu huruf saja",
    bitsChanged: (n) => `${n}/256 bit berubah`,
    avalancheNote: "Coba ganti \"Satoshi\" jadi \"satoshi\". Bit yang berubah rata-rata mendekati 50%.",
    miner: "Mini penambang",
    blockData: "DATA BLOK",
    defaultBlock: "Blok #1 · Alice → Bob · 1 BTC",
    zeros: "NOL DI DEPAN",
    difficulty: "Tingkat kesulitan",
    nonce: "Nonce",
    rate: "Hash/detik",
    time: "Waktu",
    start: "Mulai menambang",
    stop: "Berhenti",
    notes: {
      idle: () => "Tiap nol hex tambahan = 16× lebih sulit.",
      avg: (n) => `Rata-rata ${n} percobaan.`,
      searching: () => "Mencari nonce…",
      stopped: () => "Dihentikan.",
      found: (n) => `Blok ditemukan setelah ${n} percobaan.`,
    },
  },
  genesis: {
    eyebrow: "Bukti · Blok #0",
    title: "Verifikasi <em>blok genesis</em>",
    lede: "Header blok hanya 80 byte. Hash dua kali, balik urutan byte-nya, dan kamu akan mendapat hash yang sama persis dengan yang dihitung Satoshi pada 3 Januari 2009.",
    rows: ["Versi", "Blok sebelumnya", "Merkle root", "Waktu", "Bits (target)", "Nonce"],
    raw: "Header mentah · 80 byte",
    legend: ["versi", "prev hash", "merkle root", "waktu", "bits", "nonce"],
    button: "Hitung SHA256²",
    idle: "Tekan tombol untuk menghitung hash di browser kamu.",
    reversed: "SHA256(SHA256(header)), dibalik:",
    ok: "✓ Cocok dengan hash blok genesis. Perhatikan 10 nol di depan: itulah bukti kerja.",
    fail: "✗ Tidak cocok.",
  },
  halving: {
    eyebrow: "Halving · Kebijakan moneter",
    title: "Kelangkaan yang <em>terprogram</em>",
    lede: "Setiap 210.000 blok (sekitar empat tahun), imbalan penambang dipotong setengah. Hasilnya deret geometri yang berhenti tepat di bawah 21 juta BTC.",
    reward: "Imbalan per blok (BTC)",
    supply: "Total pasokan (juta BTC)",
    chartAria: "Grafik imbalan blok dan total pasokan per epoch halving",
    hint: "Arahkan kursor atau ketuk batang untuk detail.",
    estimated: "perkiraan",
    block: "blok",
    tip: (e, nf) => `<b>${e.year}${e.future ? " (perkiraan)" : ""}</b> · blok ${nf(e.block)} · imbalan <b>${nf(e.reward, 5)} BTC</b> · pasokan saat dimulai <b>${nf(e.supplyStart, 2)} juta</b>`,
  },
  memeTimeline: {
    eyebrow: "Bab 03 · Memecoin",
    title: "Dari lelucon ke <em>launchpad</em>",
    lede: "Perjalanan memecoin dari fork bergambar Shiba Inu sampai token yang bisa diperdagangkan di DEX beberapa detik setelah dibuat, sering jauh sebelum bursa terpusat mana pun me-listing-nya.",
    showAll: (n) => `Tampilkan semua ${n} momen`,
    showKey: "Tampilkan momen kunci saja",
    items: [
      ["6 Des 2013", "Scrypt", true, "Dogecoin: memecoin pertama", "Billy Markus dan Jackson Palmer memasang meme Shiba Inu \"doge\" di atas kode turunan Litecoin. Dibuat sebagai lelucon, dalam hitungan minggu sudah punya komunitas sungguhan."],
      ["Jan 2014", "", false, "Doge mengirim tim bobsled ke Sochi", "Komunitas mengumpulkan puluhan ribu dolar dalam DOGE agar tim bobsled Jamaika bisa tampil di Olimpiade Musim Dingin. Sebuah meme terbukti bisa menggerakkan orang."],
      ["2 Nov 2018", "Uniswap v1", true, "Siapa pun bisa me-listing token", "Uniswap meluncur di Ethereum dengan automated market maker x·y=k. Tanpa order book dan tanpa persetujuan listing: buat pool, token langsung bisa diperdagangkan. Semua peluncuran memecoin setelahnya bertumpu pada ini."],
      ["Mei 2020", "Uniswap v2", false, "Pasangan token langsung", "Dua token ERC-20 apa pun kini bisa dipasangkan langsung. Membakar atau mengunci LP token menjadi janji standar \"likuiditas terkunci\"."],
      ["Agu 2020", "SHIB", true, "Shiba Inu, si \"pembunuh Dogecoin\"", "Pembuat anonim bernama \"Ryoshi\" meluncurkan SHIB langsung ke pool Uniswap dan mengirim separuh pasokannya ke Vitalik Buterin. Tanpa bursa, tanpa presale: hanya sebuah pool."],
      ["Sep 2020", "BSC", false, "PancakeSwap dan gas murah", "BNB Smart Chain dan PancakeSwap menawarkan model yang sama dengan biaya jauh lebih murah dari Ethereum, membuka jalan bagi ribuan peluncuran berbiaya rendah."],
      ["Mar 2021", "", false, "SafeMoon dan token reflection", "SafeMoon meluncur di PancakeSwap dengan pajak transaksi 10% yang sebagian dibagikan ke holder. Pada November 2023 jaksa AS mendakwa para eksekutifnya atas penipuan."],
      ["8 Mei 2021", "DOGE", true, "Puncak Dogecoin di malam SNL", "Didorong terutama oleh unggahan Elon Musk, DOGE mencapai sekitar US$0,73 pada hari ia menjadi pembawa acara Saturday Night Live."],
      ["10 Mei 2021", "Binance", true, "SHIB masuk Binance", "Sembilan bulan setelah pool Uniswap-nya dibuat, SHIB listing di Binance. Beberapa hari kemudian Vitalik membakar sekitar 410 triliun SHIB (≈ US$6,7 miliar), setelah menyumbangkan 50 triliun ke dana bantuan COVID-19 India."],
      ["Okt – Nov 2021", "Honeypot", false, "Token Squid Game", "SQUID menumpang hype serial Netflix di BSC, tetapi kontraknya membuat sebagian besar holder tidak bisa menjual. Pada 1 November pengembangnya mencairkan dana dan harganya jatuh hampir ke nol."],
      ["25 Des 2022", "Solana", true, "Airdrop BONK", "Saat Solana terpuruk setelah FTX runtuh, separuh pasokan BONK di-airdrop ke komunitas Solana. BONK menjadi memecoin besar pertama di chain itu."],
      ["15 Apr 2023", "PEPE", true, "PEPE: 20 hari dari Uniswap ke Binance", "Tanpa pajak, tanpa presale, hanya pool Uniswap. Binance me-listing-nya pada 5 Mei dan kapitalisasi pasarnya menembus US$1 miliar."],
      ["15 Des 2023", "Binance", false, "BONK listing di Binance", "Hampir setahun setelah airdrop, BONK masuk Binance dengan Seed Tag berisiko tinggi."],
      ["19 Jan 2024", "pump.fun", true, "pump.fun: luncurkan dengan satu klik", "Siapa pun bisa membuat token Solana dengan biaya beberapa sen. Token diperdagangkan di bonding curve dan, pada kapitalisasi sekitar US$69.000, \"lulus\" ke pool Raydium."],
      ["5 Mar 2024", "WIF", false, "dogwifhat masuk Binance", "Diluncurkan di DEX Solana pada November 2023, anjing bertopi kupluk merah muda ini listing di Binance sekitar tiga setengah bulan kemudian."],
      ["16 Mar 2024", "BOME", false, "BOOK OF MEME dalam dua hari", "BOME melaju dari peluncuran di Solana ke listing Binance dalam sekitar dua hari, perjalanan DEX ke CEX tercepat di siklus itu."],
      ["11 Nov 2024", "Meme AI", false, "Binance me-listing ACT dan PNUT", "ACT, yang dibuat di pump.fun, dan PNUT melonjak berlipat-lipat saat pengumuman. Bursa tier-1 kini mengambil token launchpad dalam hitungan minggu."],
      ["17 Jan 2025", "TRUMP", true, "Koin resmi TRUMP", "Diluncurkan di Solana tiga hari sebelum pelantikan, kapitalisasinya menembus US$13 miliar dalam kurang dari dua hari, lalu sebagian besar nilainya hilang lagi."],
      ["14 Feb 2025", "LIBRA", false, "Skandal LIBRA", "Token yang dipromosikan Presiden Argentina Javier Milei jatuh lebih dari 90% dalam hitungan jam ketika dompet-dompet awal menjual."],
      ["20 Mar 2025", "PumpSwap", false, "pump.fun membangun DEX sendiri", "Token yang lulus kini pindah ke PumpSwap alih-alih Raydium, secara instan dan tanpa biaya migrasi, dengan biaya trading yang dibagi ke pembuat token."],
    ],
  },
  memes: {
    lifecycle: {
      eyebrow: "Sebelum CEX",
      title: "Dari <em>DEX</em> ke Binance",
      lede: "Hampir setiap memecoin sejak 2020 dimulai di bursa terdesentralisasi. Inilah tahap-tahap yang dilaluinya sebelum masuk bursa terpusat, kalau memang sampai.",
      steps: [
        ["Pembuatan", "Kontrak di-deploy, atau launchpad mencetak token dengan pasokan tetap (1 miliar di pump.fun). Biayanya beberapa sen di Solana, lebih mahal di Ethereum."],
        ["Bonding curve", "Di launchpad, setiap pembelian menaikkan harga mengikuti kurva yang sudah ditentukan. Saat kurva penuh (sekitar US$69K di pump.fun), token lulus."],
        ["Pool DEX", "Likuiditas pindah ke pool AMM di PumpSwap, Raydium, atau Uniswap. Rumus x·y=k menentukan harga, dan LP token dibakar atau dikunci."],
        ["Sniper &amp; bot", "Bot membeli di blok-blok pertama, lalu bot trading Telegram dan copy-trader ikut masuk. Siapa yang memegang lebih awal menentukan siapa yang bisa menjual ke siapa."],
        ["Trending", "Volume membawanya ke daftar trending DEX Screener dan DEXTools, lalu ke X dan Telegram. Bursa terpusat yang lebih kecil sering me-listing lebih dulu."],
        ["CEX tier-1", "Binance, OKX, atau Coinbase. Binance biasanya me-listing memecoin dengan Seed Tag yang menandainya berisiko tinggi, dan kontrak perpetual sering menyusul."],
      ],
    },
    race: {
      eyebrow: "Waktu ke Binance",
      title: "Berapa lama fase <em>DEX</em>",
      lede: "Dari transaksi DEX pertama (atau airdrop) sampai listing spot di Binance. Skala logaritmik, karena yang tercepat hanya dua hari dan yang terlama hampir setahun.",
      scale: "skala log · hari",
      rows: [
        ["BOME", "Solana", "14 Mar 2024", "16 Mar 2024", 2, "2 hari"],
        ["PEPE", "Ethereum", "15 Apr 2023", "5 Mei 2023", 20, "20 hari"],
        ["WIF", "Solana", "Nov 2023", "5 Mar 2024", 106, "± 3,5 bulan"],
        ["SHIB", "Ethereum", "Agu 2020", "10 Mei 2021", 275, "± 9 bulan"],
        ["BONK", "Solana", "25 Des 2022", "15 Des 2023", 355, "± 1 tahun"],
      ],
    },
    amm: {
      eyebrow: "Coba sendiri",
      title: "Kenapa harga <em>melompat</em>",
      lede: "Pool DEX tidak punya order book. Ia menyimpan dua cadangan dan menjaga hasil kalinya tetap, sehingga setiap pembelian membuat token berikutnya lebih mahal. Makin kecil pool-nya, makin besar lompatannya.",
      panel: "Pool constant-product",
      pool: "Pool",
      buy: "Kamu beli dengan",
      receive: "Kamu terima",
      avg: "Harga rata-rata",
      impact: "Price impact",
      after: "Harga sesudah",
      note: "x·y = k dengan biaya 0,25%, seperti AMM standar Raydium. Harga dalam SOL per sejuta MEME.",
      reserveSol: "SOL di pool",
      reserveMeme: "MEME di pool",
    },
    checklist: {
      eyebrow: "Sebelum membeli",
      title: "Checklist <em>keamanan</em> DEX",
      lede: "Sebagian besar kerugian memecoin berasal dari segelintir trik kontrak dan likuiditas. Semuanya bisa dicek on-chain dalam hitungan menit.",
      items: [
        ["Likuiditas dibakar atau dikunci", "Kalau deployer masih memegang LP token, ia bisa menarik pool dan meninggalkan holder tanpa apa-apa: rug pull."],
        ["Mint authority dicabut", "Di Solana mint authority harus null; di chain EVM ownership harus di-renounce atau tidak ada fungsi mint. Kalau tidak, pasokan baru bisa dicetak."],
        ["Freeze authority nonaktif", "Token Solana yang masih punya freeze authority bisa membekukan akun tokenmu sehingga kamu tidak bisa menjual."],
        ["Benar-benar bisa dijual", "Kontrak honeypot membolehkan beli tapi memblokir jual, seperti token Squid Game. Simulasikan penjualan sebelum membeli."],
        ["Pajak dan sebaran holder", "Cek pajak beli dan jual, serta berapa banyak yang dipegang 10 dompet teratas. Segelintir dompet yang memegang sebagian besar pasokan bisa menjatuhkan harga kapan saja."],
        ["Kontrak terverifikasi dan tidak bisa di-upgrade", "Kontrak yang tidak terverifikasi atau berbentuk proxy bisa mengubah perilakunya setelah kamu membeli."],
      ],
    },
  },
  live: {
    eyebrow: "Live · on-chain",
    title: "Bitcoin <em>saat ini</em>",
    lede: "Kondisi jaringan hari ini, ditampilkan seperti klien Bitcoin v0.1 milik Satoshi pada Januari 2009. Diperbarui setiap 30 detik.",
    latestBlock: "Blok terbaru:",
    price: "Harga:",
    halving: "Halving berikutnya:",
    network: "Jaringan:",
    halvingValue: (n, date, now, next) => `${n} blok · ≈ ${date} · imbalan ${now} → ${next} BTC`,
    networkValue: (mined, pct, diff, left) => `${mined} jt BTC tertambang (${pct}) · difficulty ${diff} dalam ${left} blok`,
    change: "24 jam",
    tab: "Blok Terbaru",
    cols: ["Status", "Tanggal", "Keterangan", "Debit", "Kredit"],
    depth: (n) => `${n} blok`,
    desc: (pool, tx, mb) => `Ditambang ${pool} · ${tx} tx · ${mb} MB`,
    unknownPool: "pool tak dikenal",
    connecting: "Menghubungkan...",
    updated: (ago) => `Diperbarui ${ago}`,
    partial: "Sebagian offline, mencoba lagi",
    error: "Offline",
    retry: "Coba lagi",
    fee: (n) => `${n} sat/vB`,
    blocks: (n) => `${n} blok`,
  },
};

export const content = { en, id };
export const LANGS = ["en", "id"];
export const PAGES = ["history", "cryptography", "memecoins", "lab"];

// Document title for a page ("" is the home page) in the given language.
export function titleFor(lang, page) {
  const t = content[lang];
  return page ? t.pages[page].docTitle : t.meta.title;
}
