// All user-facing copy, keyed by language. Strings may contain inline <em>/<code>
// markup; they are static and authored here, so rendering them as HTML is safe.

const en = {
  locale: "en-US",
  meta: {
    title: "History of Bitcoin",
    description: "The history of Bitcoin from the cypherpunk era to the fourth halving, plus the cryptography behind it: SHA-256, secp256k1, Schnorr, Merkle trees and proof-of-work. Try it live in your browser.",
  },
  skip: "Skip to content",
  nav: {
    home: "History of Bitcoin, back to top",
    brand: "History of Bitcoin",
    menu: "Menu",
    close: "Close",
    langLabel: "Language",
    links: [
      ["prolog", "Prologue"],
      ["timeline-section", "Timeline"],
      ["cryptography", "Cryptography"],
      ["lab", "Lab"],
      ["genesis", "Genesis"],
      ["halving", "Halving"],
      ["references", "References"],
    ],
  },
  hero: {
    aria: "Intro",
    quoteTitle: "Message embedded in the coinbase of block #0",
    block: "Block #0",
    title: "Money written<br>in <em>mathematics</em>",
    lede: "From a cypherpunk mailing list to a trillion-dollar network. This is the story of Bitcoin, and the cryptography behind it that you can try right on this page.",
    since: "Since genesis",
    days: "days",
    supply: "Max supply",
    hash: "Hash",
    scroll: "SCROLL",
    scrollAria: "Scroll to prologue",
  },
  prolog: {
    eyebrow: "Chapter 01 · 1976–2005",
    title: "Before Satoshi, there were <em>cypherpunks</em>",
    lede: "Bitcoin did not appear out of nowhere. Nearly three decades of cryptographic research and failed attempts at digital money prepared every ingredient.",
    items: [
      ["1976", "Public-key cryptography", "\"New Directions in Cryptography\" introduced key exchange without a pre-shared secret, the foundation of digital signatures.", "Whitfield Diffie & Martin Hellman"],
      ["1982", "Blind signatures &amp; eCash", "Chaum designed untraceable payments. DigiCash (1989) turned the idea into a product, but it still depended on a single central server.", "David Chaum"],
      ["1985", "Elliptic curve cryptography", "Proposed independently by two researchers. ECC offers security comparable to RSA with much shorter keys.", "Neal Koblitz & Victor Miller"],
      ["1991", "Timestamped hash chains", "Documents are timestamped and linked by hashes so their history cannot be altered. This work is cited three times in the Bitcoin whitepaper.", "Stuart Haber & W. Scott Stornetta"],
      ["1992", "The Cypherpunks mailing list", "A community that believed privacy must be defended with code. \"A Cypherpunk's Manifesto\" followed the next year.", "Eric Hughes, Timothy May, John Gilmore"],
      ["1997", "Hashcash", "Proof-of-work to fight email spam. Satoshi used the same mechanism to secure the blockchain.", "Adam Back"],
      ["1998", "b-money", "A proposal for distributed money with a shared ledger and money created through computation. Cited directly in the whitepaper.", "Wei Dai"],
      ["2004 – 2005", "RPOW &amp; Bit Gold", "Reusable proof-of-work tokens, and hash-chained \"digital gold\". Both came close to solving the double-spend problem.", "Hal Finney · Nick Szabo"],
    ],
  },
  quote: {
    text: "\"A purely peer-to-peer version of electronic cash would allow online payments to be sent directly from one party to another without going through a financial institution.\"",
    cite: "Satoshi Nakamoto · Bitcoin Whitepaper, 2008",
  },
  timeline: {
    eyebrow: "Chapter 02 · 2008–today",
    title: "The <em>Bitcoin</em> timeline",
    lede: "The moments that shaped the network: from a nine-page PDF to ETFs on Wall Street.",
    // [date, tag, hot, title, text]
    items: [
      ["18 Aug 2008", "bitcoin.org", false, "bitcoin.org is registered", "Two months before the whitepaper circulated, the stage was set anonymously."],
      ["31 Oct 2008", "Whitepaper", true, "\"Bitcoin: A Peer-to-Peer Electronic Cash System\"", "Satoshi Nakamoto posts a nine-page paper to the cryptography mailing list. It solves the double-spend problem without a trusted third party, using proof-of-work and a chain of blocks."],
      ["3 Jan 2009", "Block #0", true, "The genesis block is mined", "Its 50 BTC reward can never be spent. The Times headline in its coinbase serves as both a timestamp and a statement."],
      ["9 Jan 2009", "v0.1", false, "Bitcoin v0.1 is released", "The first open-source software, for Windows. Anyone can run a node and mine."],
      ["12 Jan 2009", "Block #170", false, "First transaction: Satoshi → Hal Finney", "10 BTC changes hands. Finney, creator of RPOW, is the first person besides Satoshi to run a node."],
      ["5 Oct 2009", "", false, "First price: US$1 = 1,309.03 BTC", "New Liberty Standard derives an exchange rate from the electricity cost of mining one bitcoin."],
      ["22 May 2010", "Pizza Day", true, "10,000 BTC for two pizzas", "Laszlo Hanyecz makes the first documented purchase of real goods with bitcoin. The date is still celebrated every year."],
      ["15 Aug 2010", "Block #74,638", false, "The value overflow incident", "An integer overflow bug creates 184 billion BTC. Within hours a patch is released and the chain is forked back. It remains the only major inflation bug ever exploited."],
      ["Dec 2010 – Apr 2011", "", false, "Satoshi disappears", "The last forum post is on 12 December 2010. Control of the project passes to Gavin Andresen, and Satoshi is never heard from again."],
      ["28 Nov 2012", "Halving 1", false, "Block reward drops 50 → 25 BTC", "Monetary policy written in code executes exactly on schedule at block 210,000."],
      ["Feb 2014", "", false, "The collapse of Mt. Gox", "The exchange that once handled most of the world's volume loses around 850,000 BTC. A lesson repeated ever since: <em>not your keys, not your coins</em>."],
      ["9 Jul 2016", "Halving 2", false, "Block reward drops to 12.5 BTC", "Block 420,000. The network matures and the scaling debate heats up."],
      ["24 Aug 2017", "SegWit", true, "Segregated Witness activates", "A soft fork at block 481,824 fixes transaction malleability and paves the way for Lightning. Three weeks earlier, the big-block camp split off as Bitcoin Cash."],
      ["Mar 2018", "Layer 2", false, "Lightning Network goes live on mainnet", "Off-chain payment channels for instant, cheap transactions, still secured by the Bitcoin blockchain."],
      ["11 May 2020", "Halving 3", false, "Block reward drops to 6.25 BTC", "It happens amid a pandemic and massive monetary stimulus. The \"digital gold\" narrative grows stronger."],
      ["7 Sep 2021", "", false, "El Salvador makes it legal tender", "The first country to adopt bitcoin as official currency alongside the US dollar."],
      ["14 Nov 2021", "Taproot", true, "Taproot &amp; Schnorr signatures", "The biggest upgrade since SegWit, active at block 709,632. BIPs 340–342 bring aggregatable signatures and more private scripts."],
      ["10 Jan 2024", "ETF", false, "SEC approves spot bitcoin ETFs", "Eleven products begin trading the next day. Bitcoin officially enters mainstream institutional portfolios."],
      ["20 Apr 2024", "Halving 4", false, "Block reward drops to 3.125 BTC", "Block 840,000. More than 93% of all 21 million BTC have been mined."],
      ["± 2140", "Last satoshi", false, "The last bitcoin is mined", "After 33 halvings, the block subsidy reaches zero. Miners are paid by transaction fees alone."],
    ],
  },
  crypto: {
    eyebrow: "Chapter 03 · Primitives",
    title: "Trust, replaced by <em>cryptography</em>",
    lede: "Bitcoin invented no new algorithms. It assembled primitives tested over decades into a system that needs no central authority.",
    curveAria: "Plot of the elliptic curve y² = x³ + 7 over the real numbers",
    merkleAria: "Merkle tree diagram with four transactions",
    cards: {
      hash: {
        kicker: "01 · Hash function",
        title: "SHA-256, applied twice",
        body: [
          "Everything in Bitcoin is identified by a hash: blocks, transactions, even addresses. SHA-256 is deterministic and one-way. Flip one input bit and on average half the output bits change (the <em>avalanche effect</em>).",
          "Bitcoin uses <code>SHA256(SHA256(x))</code> for block and transaction IDs, as a defense against length-extension attacks.",
        ],
        spec: "FIPS 180-4 · 256-bit output · 64 compression rounds · NSA/NIST 2001",
      },
      pow: {
        kicker: "02 · Proof-of-Work",
        title: "A lottery that cannot be rigged",
        body: [
          "Miners vary the <code>nonce</code> until the block header hash falls below a target. The only way is to keep trying, so rewriting history costs more energy than the entire network.",
          "The target adjusts every 2,016 blocks so that one block is found roughly every 10 minutes.",
        ],
        spec: "hash(header) &lt; target · retarget every 2016 blocks",
      },
      ecdsa: {
        kicker: "03 · Digital signatures",
        title: "ECDSA on the secp256k1 curve",
        body: ["A private key is a random 256-bit number <code>k</code>. The public key <code>K = k·G</code> is easy to compute, but reversing it (the discrete logarithm problem) is practically impossible."],
        spec: "y² = x³ + 7 (mod p) · p = 2²⁵⁶ − 2³² − 977 · SEC 2",
      },
      merkle: {
        kicker: "04 · Data structure",
        title: "Merkle tree",
        body: ["Thousands of transactions are summarized into a single 32-byte hash in the header. Light (SPV) wallets only need a <em>Merkle proof</em> of length log₂(n) to prove a transaction is in a block."],
        spec: "Merkle 1979 · whitepaper §7–8",
      },
      schnorr: {
        kicker: "05 · Taproot",
        title: "Schnorr signatures",
        body: ["Linear, aggregatable signatures: a multisig transaction looks just like a regular one. Smaller, more private, and provably secure."],
        spec: "BIP 340 · 64 bytes · active Nov 2021",
      },
      address: {
        kicker: "06 · Addresses",
        title: "HASH160 &amp; Bech32",
        body: ["The public key is hashed with <code>RIPEMD160(SHA256(K))</code> and then encoded. Base58Check avoids look-alike characters (0/O, l/I); Bech32 adds BCH error detection."],
        spec: "1… legacy · 3… P2SH · bc1q… SegWit · bc1p… Taproot",
      },
      wallet: {
        kicker: "07 · Wallets",
        title: "HD wallets &amp; seed phrases",
        body: ["A single 12–24 word seed (BIP 39) derives an unlimited tree of keys via HMAC-SHA512 (BIP 32). Back up once, recover everything."],
        spec: "BIP 32 · BIP 39 · BIP 44/84/86",
      },
    },
  },
  lab: {
    eyebrow: "Chapter 04 · Try it yourself",
    title: "The <em>hash</em> lab",
    lede: "Everything is computed locally in your browser with a pure JavaScript SHA-256 implementation. No data is sent anywhere.",
    avalanche: "Avalanche effect",
    input: "INPUT",
    output: "OUTPUT · 64 HEX",
    defaultInput: "Satoshi Nakamoto",
    changeOne: "Change a single letter",
    bitsChanged: (n) => `${n}/256 bits changed`,
    avalancheNote: "Try changing \"Satoshi\" to \"satoshi\". On average, close to 50% of the bits change.",
    miner: "Mini miner",
    blockData: "BLOCK DATA",
    defaultBlock: "Block #1 · Alice → Bob · 1 BTC",
    zeros: "LEADING ZEROS",
    difficulty: "Difficulty",
    nonce: "Nonce",
    rate: "Hashes/sec",
    time: "Time",
    start: "Start mining",
    stop: "Stop",
    notes: {
      idle: () => "Each extra hex zero = 16× harder.",
      avg: (n) => `${n} attempts on average.`,
      searching: () => "Searching for a nonce…",
      stopped: () => "Stopped.",
      found: (n) => `Block found after ${n} attempts.`,
    },
  },
  genesis: {
    eyebrow: "Chapter 05 · Block #0",
    title: "Verify the <em>genesis block</em>",
    lede: "A block header is only 80 bytes. Hash it twice, reverse the byte order, and you get exactly the same hash Satoshi computed on 3 January 2009.",
    rows: ["Version", "Previous block", "Merkle root", "Time", "Bits (target)", "Nonce"],
    raw: "Raw header · 80 bytes",
    legend: ["version", "prev hash", "merkle root", "time", "bits", "nonce"],
    button: "Compute SHA256²",
    idle: "Press the button to compute the hash in your browser.",
    reversed: "SHA256(SHA256(header)), reversed:",
    ok: "✓ Matches the genesis block hash. Note the 10 leading zeros: that is the proof of work.",
    fail: "✗ No match.",
  },
  halving: {
    eyebrow: "Chapter 06 · Monetary policy",
    title: "<em>Programmed</em> scarcity",
    lede: "Every 210,000 blocks (about four years), the miner reward is cut in half. The result is a geometric series that converges just below 21 million BTC.",
    reward: "Block reward (BTC)",
    supply: "Total supply (million BTC)",
    chartAria: "Chart of block reward and total supply per halving epoch",
    hint: "Hover or tap a bar for details.",
    estimated: "estimated",
    block: "block",
    tip: (e, nf) => `<b>${e.year}${e.future ? " (estimated)" : ""}</b> · block ${nf(e.block)} · reward <b>${nf(e.reward, 5)} BTC</b> · supply at end of epoch <b>${nf(e.supply, 2)} million</b>`,
  },
  refs: {
    eyebrow: "Chapter 07 · Sources",
    title: "<em>Open</em> references",
    lede: "This page is built from source code, specifications and primary documents you can read yourself.",
    github: "GitHub · open source",
    docs: "Documents &amp; specifications",
    githubItems: [
      "Bitcoin Core, the reference implementation since 2009",
      "Bitcoin Improvement Proposals: SegWit, Taproot, BIP 32/39",
      "Optimized C library for ECDSA &amp; Schnorr",
      "Mastering Bitcoin, Andreas M. Antonopoulos &amp; David A. Harding",
      "Lightning Network specifications",
      "Open-source block explorer &amp; visualizer",
    ],
    docItems: [
      "Satoshi Nakamoto, 31 October 2008",
      "Archive of emails, forum posts, and cypherpunk literature",
      "Protocol reference, block &amp; transaction formats",
      "Visual technical explanations, including the genesis block",
      "Secure Hash Standard (SHA-256)",
      "Official secp256k1 curve parameters",
    ],
  },
  footer: "Made for education. Not financial advice.",
};

const id = {
  locale: "id-ID",
  meta: {
    title: "Sejarah Bitcoin",
    description: "Sejarah Bitcoin dari era cypherpunk hingga halving keempat, plus kriptografi di baliknya: SHA-256, secp256k1, Schnorr, Merkle tree dan proof-of-work. Bisa dicoba langsung di browser.",
  },
  skip: "Lompat ke konten",
  nav: {
    home: "Sejarah Bitcoin, ke atas",
    brand: "Sejarah Bitcoin",
    menu: "Menu",
    close: "Tutup",
    langLabel: "Bahasa",
    links: [
      ["prolog", "Prolog"],
      ["timeline-section", "Lini Masa"],
      ["cryptography", "Kriptografi"],
      ["lab", "Lab"],
      ["genesis", "Genesis"],
      ["halving", "Halving"],
      ["references", "Referensi"],
    ],
  },
  hero: {
    aria: "Pembuka",
    quoteTitle: "Pesan yang tertanam di coinbase blok #0",
    block: "Blok #0",
    title: "Uang yang ditulis<br>dengan <em>matematika</em>",
    lede: "Dari milis cypherpunk hingga jaringan bernilai triliunan dolar. Ini kisah Bitcoin, dan kriptografi di baliknya yang bisa kamu coba langsung di halaman ini.",
    since: "Sejak genesis",
    days: "hari",
    supply: "Pasokan maks",
    hash: "Hash",
    scroll: "GULIR",
    scrollAria: "Gulir ke prolog",
  },
  prolog: {
    eyebrow: "Bab 01 · 1976–2005",
    title: "Sebelum Satoshi, ada <em>cypherpunk</em>",
    lede: "Bitcoin tidak muncul tiba-tiba. Hampir tiga dekade riset kriptografi dan upaya uang digital yang gagal menyiapkan semua bahannya.",
    items: [
      ["1976", "Kriptografi kunci publik", "Makalah \"New Directions in Cryptography\" memperkenalkan pertukaran kunci tanpa rahasia bersama, fondasi tanda tangan digital.", "Whitfield Diffie & Martin Hellman"],
      ["1982", "Blind signatures &amp; eCash", "Chaum merancang pembayaran yang tidak bisa dilacak. Lewat DigiCash (1989) idenya jadi produk, tapi masih bergantung pada satu server pusat.", "David Chaum"],
      ["1985", "Kriptografi kurva eliptik", "Diusulkan secara terpisah oleh dua peneliti. ECC menawarkan keamanan setara RSA dengan kunci yang jauh lebih pendek.", "Neal Koblitz & Victor Miller"],
      ["1991", "Rantai hash bertanda waktu", "Dokumen diberi stempel waktu dan dirangkai dengan hash sehingga riwayatnya tidak bisa diubah. Makalah ini dikutip tiga kali di whitepaper Bitcoin.", "Stuart Haber & W. Scott Stornetta"],
      ["1992", "Milis Cypherpunks", "Komunitas yang percaya privasi harus dijaga dengan kode. \"A Cypherpunk's Manifesto\" terbit tahun berikutnya.", "Eric Hughes, Timothy May, John Gilmore"],
      ["1997", "Hashcash", "Proof-of-work untuk melawan spam email. Satoshi memakai mekanisme yang sama untuk mengamankan blockchain.", "Adam Back"],
      ["1998", "b-money", "Usulan uang terdistribusi dengan buku besar bersama dan pembuatan uang lewat komputasi. Dikutip langsung di whitepaper.", "Wei Dai"],
      ["2004 – 2005", "RPOW &amp; Bit Gold", "Token proof-of-work yang bisa dipakai ulang, dan \"emas digital\" berantai hash. Keduanya hampir menyelesaikan masalah double-spend.", "Hal Finney · Nick Szabo"],
    ],
  },
  quote: en.quote,
  timeline: {
    eyebrow: "Bab 02 · 2008–sekarang",
    title: "Lini masa <em>Bitcoin</em>",
    lede: "Momen yang membentuk jaringan: dari sembilan halaman PDF sampai ETF di Wall Street.",
    items: [
      ["18 Agu 2008", "bitcoin.org", false, "Domain bitcoin.org didaftarkan", "Dua bulan sebelum whitepaper beredar, panggungnya sudah disiapkan secara anonim."],
      ["31 Okt 2008", "Whitepaper", true, "\"Bitcoin: A Peer-to-Peer Electronic Cash System\"", "Satoshi Nakamoto mengirim makalah sembilan halaman ke milis kriptografi. Isinya menjawab masalah double-spend tanpa pihak ketiga, dengan proof-of-work dan rantai blok."],
      ["3 Jan 2009", "Blok #0", true, "Blok genesis ditambang", "Imbalan 50 BTC yang tidak akan pernah bisa dibelanjakan. Judul koran The Times di coinbase-nya jadi stempel waktu sekaligus pernyataan sikap."],
      ["9 Jan 2009", "v0.1", false, "Bitcoin v0.1 dirilis", "Perangkat lunak open source pertama untuk Windows. Siapa pun bisa menjalankan node dan menambang."],
      ["12 Jan 2009", "Blok #170", false, "Transaksi pertama: Satoshi → Hal Finney", "10 BTC berpindah tangan. Finney, yang sebelumnya membuat RPOW, menjadi orang pertama selain Satoshi yang menjalankan node."],
      ["5 Okt 2009", "", false, "Harga pertama: US$1 = 1.309,03 BTC", "New Liberty Standard menghitung kurs dari biaya listrik untuk menambang satu bitcoin."],
      ["22 Mei 2010", "Pizza Day", true, "10.000 BTC untuk dua pizza", "Laszlo Hanyecz melakukan pembelian barang nyata pertama yang terdokumentasi dengan bitcoin. Tanggal ini masih dirayakan tiap tahun."],
      ["15 Agu 2010", "Blok #74.638", false, "Insiden value overflow", "Bug integer overflow menciptakan 184 miliar BTC. Dalam beberapa jam patch dirilis dan rantai di-fork kembali. Ini satu-satunya bug inflasi besar yang pernah dieksploitasi."],
      ["Des 2010 – Apr 2011", "", false, "Satoshi menghilang", "Postingan forum terakhir pada 12 Desember 2010. Kendali proyek diserahkan ke Gavin Andresen, lalu Satoshi tidak pernah muncul lagi."],
      ["28 Nov 2012", "Halving 1", false, "Imbalan blok turun 50 → 25 BTC", "Kebijakan moneter yang tertulis di kode berjalan persis sesuai jadwal di blok 210.000."],
      ["Feb 2014", "", false, "Runtuhnya Mt. Gox", "Bursa yang pernah memproses sebagian besar volume dunia kehilangan sekitar 850.000 BTC. Pelajaran yang terus diulang: <em>not your keys, not your coins</em>."],
      ["9 Jul 2016", "Halving 2", false, "Imbalan blok turun ke 12,5 BTC", "Blok 420.000. Jaringan makin matang dan perdebatan soal skalabilitas memanas."],
      ["24 Agu 2017", "SegWit", true, "Segregated Witness aktif", "Soft fork di blok 481.824 memperbaiki malleability transaksi dan membuka jalan bagi Lightning. Tiga minggu sebelumnya, kubu blok besar memisahkan diri sebagai Bitcoin Cash."],
      ["Mar 2018", "Layer 2", false, "Lightning Network di mainnet", "Kanal pembayaran off-chain untuk transaksi instan dan murah, tetap dijamin oleh blockchain Bitcoin."],
      ["11 Mei 2020", "Halving 3", false, "Imbalan blok turun ke 6,25 BTC", "Terjadi di tengah pandemi dan stimulus moneter besar-besaran. Narasi \"emas digital\" makin menguat."],
      ["7 Sep 2021", "", false, "El Salvador: alat pembayaran sah", "Negara pertama yang menjadikan bitcoin mata uang resmi di samping dolar AS."],
      ["14 Nov 2021", "Taproot", true, "Taproot &amp; tanda tangan Schnorr", "Upgrade terbesar sejak SegWit, aktif di blok 709.632. BIP 340–342 membawa tanda tangan yang bisa diagregasi dan skrip yang lebih privat."],
      ["10 Jan 2024", "ETF", false, "SEC menyetujui ETF bitcoin spot", "Sebelas produk mulai diperdagangkan keesokan harinya. Bitcoin resmi masuk portofolio institusi arus utama."],
      ["20 Apr 2024", "Halving 4", false, "Imbalan blok turun ke 3,125 BTC", "Blok 840.000. Lebih dari 93% dari 21 juta BTC sudah ditambang."],
      ["± 2140", "Satoshi terakhir", false, "Bitcoin terakhir ditambang", "Setelah 33 halving, imbalan blok menjadi nol. Penambang hanya dibayar dari biaya transaksi."],
    ],
  },
  crypto: {
    eyebrow: "Bab 03 · Primitif",
    title: "Kepercayaan diganti <em>kriptografi</em>",
    lede: "Bitcoin tidak menciptakan algoritma baru. Ia merangkai primitif yang sudah teruji puluhan tahun menjadi sistem yang tidak membutuhkan otoritas pusat.",
    curveAria: "Grafik kurva eliptik y² = x³ + 7 di bilangan real",
    merkleAria: "Diagram Merkle tree dengan empat transaksi",
    cards: {
      hash: {
        kicker: "01 · Fungsi hash",
        title: "SHA-256, dijalankan dua kali",
        body: [
          "Semua hal di Bitcoin diidentifikasi dengan hash: blok, transaksi, sampai alamat. SHA-256 bersifat deterministik dan satu arah. Ubah satu bit input, dan rata-rata separuh bit output ikut berubah (<em>avalanche effect</em>).",
          "Bitcoin memakai <code>SHA256(SHA256(x))</code> untuk ID blok dan transaksi, sebagai pertahanan terhadap serangan length-extension.",
        ],
        spec: "FIPS 180-4 · output 256 bit · 64 ronde kompresi · NSA/NIST 2001",
      },
      pow: {
        kicker: "02 · Proof-of-Work",
        title: "Lotere yang tidak bisa dicurangi",
        body: [
          "Penambang mengganti <code>nonce</code> sampai hash header blok berada di bawah target. Satu-satunya cara adalah mencoba, sehingga menulis ulang sejarah butuh energi lebih besar dari seluruh jaringan.",
          "Target disesuaikan tiap 2.016 blok agar rata-rata satu blok lahir setiap ~10 menit.",
        ],
        spec: "hash(header) &lt; target · retarget 2016 blok",
      },
      ecdsa: {
        kicker: "03 · Tanda tangan digital",
        title: "ECDSA di kurva secp256k1",
        body: ["Kunci privat adalah angka acak 256 bit <code>k</code>. Kunci publik <code>K = k·G</code> mudah dihitung, tetapi membalikkannya (masalah logaritma diskret) mustahil secara praktis."],
        spec: en.crypto.cards.ecdsa.spec,
      },
      merkle: {
        kicker: "04 · Struktur data",
        title: "Merkle tree",
        body: ["Ribuan transaksi diringkas menjadi satu hash 32 byte di header. Dompet ringan (SPV) cukup meminta <em>Merkle proof</em> sepanjang log₂(n) untuk membuktikan sebuah transaksi ada di blok."],
        spec: en.crypto.cards.merkle.spec,
      },
      schnorr: {
        kicker: "05 · Taproot",
        title: "Schnorr signatures",
        body: ["Tanda tangan linear yang bisa diagregasi: transaksi multisig terlihat sama seperti transaksi biasa. Lebih ringkas, lebih privat, dan terbukti aman secara formal."],
        spec: "BIP 340 · 64 byte · aktif Nov 2021",
      },
      address: {
        kicker: "06 · Alamat",
        title: "HASH160 &amp; Bech32",
        body: ["Kunci publik di-hash dengan <code>RIPEMD160(SHA256(K))</code> lalu dikodekan. Base58Check menghindari karakter mirip (0/O, l/I); Bech32 menambah deteksi kesalahan BCH."],
        spec: en.crypto.cards.address.spec,
      },
      wallet: {
        kicker: "07 · Dompet",
        title: "HD wallet &amp; seed phrase",
        body: ["Satu seed 12–24 kata (BIP 39) menurunkan pohon kunci tak terbatas lewat HMAC-SHA512 (BIP 32). Cadangkan sekali, pulihkan semuanya."],
        spec: en.crypto.cards.wallet.spec,
      },
    },
  },
  lab: {
    eyebrow: "Bab 04 · Coba sendiri",
    title: "Laboratorium <em>hash</em>",
    lede: "Semua dihitung lokal di browser kamu dengan implementasi SHA-256 murni JavaScript. Tidak ada data yang dikirim ke mana pun.",
    avalanche: "Avalanche effect",
    input: "INPUT",
    output: "OUTPUT · 64 HEX",
    defaultInput: "Satoshi Nakamoto",
    changeOne: "Ubah satu huruf saja",
    bitsChanged: (n) => `${n}/256 bit berubah`,
    avalancheNote: "Coba ganti \"Satoshi\" jadi \"satoshi\". Bit yang berubah rata-rata mendekati 50%.",
    miner: "Mini penambang",
    blockData: "DATA BLOK",
    defaultBlock: "Blok #1 · Alice → Bob · 1 BTC",
    zeros: "NOL DI DEPAN",
    difficulty: "Tingkat kesulitan",
    nonce: "Nonce",
    rate: "Hash/detik",
    time: "Waktu",
    start: "Mulai menambang",
    stop: "Berhenti",
    notes: {
      idle: () => "Tiap nol hex tambahan = 16× lebih sulit.",
      avg: (n) => `Rata-rata ${n} percobaan.`,
      searching: () => "Mencari nonce…",
      stopped: () => "Dihentikan.",
      found: (n) => `Blok ditemukan setelah ${n} percobaan.`,
    },
  },
  genesis: {
    eyebrow: "Bab 05 · Blok #0",
    title: "Verifikasi <em>blok genesis</em>",
    lede: "Header blok hanya 80 byte. Hash dua kali, balik urutan byte-nya, dan kamu akan mendapat hash yang sama persis dengan yang dihitung Satoshi pada 3 Januari 2009.",
    rows: ["Versi", "Blok sebelumnya", "Merkle root", "Waktu", "Bits (target)", "Nonce"],
    raw: "Header mentah · 80 byte",
    legend: ["versi", "prev hash", "merkle root", "waktu", "bits", "nonce"],
    button: "Hitung SHA256²",
    idle: "Tekan tombol untuk menghitung hash di browser kamu.",
    reversed: "SHA256(SHA256(header)), dibalik:",
    ok: "✓ Cocok dengan hash blok genesis. Perhatikan 10 nol di depan: itulah bukti kerja.",
    fail: "✗ Tidak cocok.",
  },
  halving: {
    eyebrow: "Bab 06 · Kebijakan moneter",
    title: "Kelangkaan yang <em>terprogram</em>",
    lede: "Setiap 210.000 blok (sekitar empat tahun), imbalan penambang dipotong setengah. Hasilnya deret geometri yang berhenti tepat di bawah 21 juta BTC.",
    reward: "Imbalan per blok (BTC)",
    supply: "Total pasokan (juta BTC)",
    chartAria: "Grafik imbalan blok dan total pasokan per epoch halving",
    hint: "Arahkan kursor atau ketuk batang untuk detail.",
    estimated: "perkiraan",
    block: "blok",
    tip: (e, nf) => `<b>${e.year}${e.future ? " (perkiraan)" : ""}</b> · blok ${nf(e.block)} · imbalan <b>${nf(e.reward, 5)} BTC</b> · pasokan di akhir epoch <b>${nf(e.supply, 2)} juta</b>`,
  },
  refs: {
    eyebrow: "Bab 07 · Sumber",
    title: "Referensi <em>terbuka</em>",
    lede: "Halaman ini disusun dari kode sumber, spesifikasi dan dokumen primer yang bisa kamu baca sendiri.",
    github: "GitHub · open source",
    docs: "Dokumen &amp; spesifikasi",
    githubItems: [
      "Bitcoin Core, implementasi referensi sejak 2009",
      "Bitcoin Improvement Proposals: SegWit, Taproot, BIP 32/39",
      "Pustaka C teroptimasi untuk ECDSA &amp; Schnorr",
      "Mastering Bitcoin, Andreas M. Antonopoulos &amp; David A. Harding",
      "Spesifikasi Lightning Network",
      "Explorer &amp; visualisasi blok open source",
    ],
    docItems: [
      "Satoshi Nakamoto, 31 Oktober 2008",
      "Arsip email, postingan forum, dan literatur cypherpunk",
      "Referensi protokol, format blok &amp; transaksi",
      "Penjelasan teknis visual, termasuk blok genesis",
      "Secure Hash Standard (SHA-256)",
      "Parameter resmi kurva secp256k1",
    ],
  },
  footer: "Dibuat untuk edukasi. Bukan saran keuangan.",
};

export const content = { en, id };
export const LANGS = ["en", "id"];
