// Copy for Satoshi's Wallet. Node and choice ids match lib/story.js. Each node has
// [date, title] plus text per variant ("default" when the node has none).

const en = {
  eyebrow: "Chapter 02 · Play",
  title: "Satoshi's <em>Wallet</em>",
  lede: "Live through Bitcoin's history with real prices. Pick who you are, make the calls people actually faced, and see what your coins would be worth today.",
  pick: "Choose your starting point",
  personas: {
    miner: ["The miner", "January 2009", "You read the whitepaper and start mining on your laptop. You have no coins yet."],
    early: ["The early adopter", "May 2010", "You bought 5,000 BTC on a forum for about $20."],
    trader: ["The trader", "April 2013", "You put $10,000 into bitcoin on Mt. Gox at $161."],
    newcomer: ["The newcomer", "December 2017", "Everyone is talking about it. You buy $10,000 worth near $19,250."],
  },
  resume: "Continue where you left off",
  restart: "Start over",
  step: (n, total) => `Moment ${n} of ${total}`,
  context: "See this moment in the Time Machine",
  holdings: "Your wallet",
  btc: "Bitcoin",
  cash: "Cash",
  value: "Value then",
  where: "Kept",
  custody: { self: "Your own keys", exchange: "On an exchange", lender: "With a crypto lender", etf: "ETF shares" },
  noPrice: "no price yet",
  nodes: {
    mine: {
      head: ["Jan 2009", "Mining at difficulty 1"],
      default: "Bitcoin v0.1 is out. Difficulty is 1, and a laptop finds a 50 BTC block every so often. Mining costs only electricity, and nobody is buying.",
      choices: { month: "Leave it running for a month", once: "Mine one block for fun, then switch off" },
    },
    pizza: {
      head: ["22 May 2010", "Laszlo wants pizza"],
      default: "On the forum, Laszlo has just paid 10,000 BTC for two pizzas. Bitcoin finally buys something. Do you join in and spend some?",
      choices: { spend: "Spend 10% on pizza and games", keep: "Keep every coin" },
    },
    parity: {
      head: ["9 Feb 2011", "One bitcoin, one dollar"],
      default: "Bitcoin hits $1 on Mt. Gox. A year ago it was a fraction of a cent. Your coins are suddenly real money.",
      choices: { sellHalf: "Sell half and lock in the gain", hold: "Hold" },
    },
    backup: {
      head: ["Jun 2012", "Where is your wallet.dat?"],
      default: "Your coins live in a single file on your laptop. The forum keeps warning: encrypt it and back it up, or one dead disk takes everything.",
      choices: { backup: "Encrypt it and back it up to USB and paper", later: "I'll do it later" },
    },
    exchange: {
      head: ["Apr 2013", "Mt. Gox handles 70% of all trades"],
      default: "Prices swing hard and Mt. Gox is where the action is. Keeping coins there makes trading easy. Withdrawals have been slow lately, though.",
      choices: { gox: "Keep the coins on Mt. Gox", self: "Move them to my own wallet" },
    },
    laptop: {
      head: ["Nov 2013", "Bitcoin passes $1,000"],
      risk: "Bitcoin is above $1,000, but your old laptop died months ago and you never made a backup. It is sitting in a bag by the door with the rest of the junk.",
      safe: "Bitcoin is above $1,000, more than tenfold in a year. The news is full of it. Take some profit?",
      choices: { trash: "Throw the bag out", search: "Dig through the old drive first", sellHalf: "Sell half", hold: "Hold" },
    },
    gox: {
      head: ["Feb 2014", "Mt. Gox goes dark"],
      hit: "Withdrawals halt on 7 February. On the 28th Mt. Gox files for bankruptcy with about 850,000 BTC missing, yours included. Repayments will start only in 2024.",
      safe: "Withdrawals halt on 7 February and Mt. Gox files for bankruptcy on the 28th, with about 850,000 BTC missing. Your coins are not there.",
      choices: { self: "Keep my coins on my own keys from now on", another: "Use another exchange" },
    },
    fork: {
      head: ["1 Aug 2017", "Bitcoin Cash forks off"],
      has: "The big-block camp splits off as Bitcoin Cash, and you receive one BCH for each BTC you hold. One BCH trades for about 0.127 BTC.",
      none: "The big-block camp splits off as Bitcoin Cash. With no bitcoin in your wallet, you receive nothing.",
      choices: { swap: "Sell the BCH for more BTC", ignore: "Ignore it", continue: "Continue" },
    },
    mania: {
      head: ["17 Dec 2017", "Bitcoin near $20,000"],
      default: "Your taxi driver asks about bitcoin. Fees top $50. An exchange offers 3× leverage with one click.",
      choices: { sellHalf: "Sell half", hold: "Hold", leverage: "Go 3× leveraged" },
    },
    winter: {
      head: ["15 Dec 2018", "Crypto winter: −84%"],
      liquidated: "In February the price fell by a third and your 3× position was liquidated: every coin you put up is gone. Now bitcoin sits near $3,200.",
      normal: "A year after the peak, bitcoin trades near $3,200. Headlines declare it dead, again.",
      choices: { sellAll: "Sell everything", hold: "Hold", buy: "Buy $1,000 more" },
    },
    covid: {
      head: ["12 Mar 2020", "Black Thursday"],
      default: "A pandemic shuts down the world and markets panic. Bitcoin loses about 40% in a single day, to under $5,000.",
      choices: { sellAll: "Sell everything", hold: "Hold", buy: "Buy $1,000 more" },
    },
    yield: {
      head: ["Nov 2021", "Near $69,000 and 8% a year"],
      default: "A slick crypto lender offers 8% interest on deposited bitcoin. Millions of people use it. Your keys sit there earning nothing.",
      choices: { deposit: "Deposit my coins for 8%", keep: "Keep my own keys" },
    },
    ftx: {
      head: ["Nov 2022", "Lenders and FTX collapse"],
      hit: "Your lender freezes withdrawals and files for bankruptcy. Claims are valued in dollars at the filing date, so years later you get cash at the bottom of the market, not your coins.",
      safe: "Celsius, then FTX: one platform after another freezes withdrawals. Your coins are not on any of them.",
      choices: { self: "Hold my own keys", exchange: "Keep using an exchange" },
    },
    etf: {
      head: ["Jan 2024", "Spot ETFs arrive"],
      has: "Spot bitcoin ETFs start trading. You could swap your coins for fund shares in a normal brokerage account: no keys, no seed phrase, a small yearly fee.",
      none: "Spot bitcoin ETFs start trading at about $46,000. Buy back in?",
      choices: { etf: "Swap to ETF shares", keys: "Keep my keys", buy: "Buy $1,000 of bitcoin", skip: "Stay out" },
    },
  },
  result: {
    eyebrow: "Today",
    title: "Where your choices led",
    worth: "Your wallet is worth",
    hodl: "If you had held from the start",
    invested: "Money you put in",
    lost: "Bitcoin you lost",
    priceLive: (p) => `At the live price of ${p}`,
    priceData: (p, m) => `At ${p}, the latest close in our data (${m})`,
    journey: "Your path",
    badges: "What you learned",
    again: "Play again",
    other: "Try another starting point",
    toTimeMachine: "Back to the Time Machine",
  },
  badges: {
    diamond: ["Diamond hands", "You never sold."],
    pizza: ["Pizza legend", "You spent bitcoin as money, like Laszlo."],
    backup: ["Backed up", "Your keys survived a dead laptop."],
    keys: ["Not your keys, not your coins", "You end the game holding your own keys."],
    etf: ["Easy mode", "ETF shares: no keys to lose, no keys to use."],
    fork: ["Fork survivor", "You turned free BCH into more bitcoin."],
    trashed: ["Landfill club", "Like James Howells, you threw away your keys."],
    gox: ["Mt. Gox victim", "Your exchange held your coins, then lost them."],
    liquidated: ["Liquidated", "Leverage turned a dip into a wipeout."],
    lender: ["Frozen", "Your lender paid you back in 2022 dollars."],
  },
};

const id = {
  eyebrow: "Bab 02 · Main",
  title: "Dompet <em>Satoshi</em>",
  lede: "Jalani sejarah Bitcoin dengan harga sungguhan. Pilih siapa kamu, ambil keputusan yang benar-benar dihadapi orang waktu itu, lalu lihat berapa nilai koinmu hari ini.",
  pick: "Pilih titik awalmu",
  personas: {
    miner: ["Si penambang", "Januari 2009", "Kamu membaca whitepaper dan mulai menambang di laptop. Belum punya koin sama sekali."],
    early: ["Si pengguna awal", "Mei 2010", "Kamu membeli 5.000 BTC di forum seharga sekitar US$20."],
    trader: ["Si trader", "April 2013", "Kamu menaruh US$10.000 ke bitcoin di Mt. Gox pada harga US$161."],
    newcomer: ["Si pendatang baru", "Desember 2017", "Semua orang membicarakannya. Kamu membeli US$10.000 di dekat US$19.250."],
  },
  resume: "Lanjutkan permainan terakhir",
  restart: "Mulai ulang",
  step: (n, total) => `Momen ${n} dari ${total}`,
  context: "Lihat momen ini di Mesin Waktu",
  holdings: "Dompetmu",
  btc: "Bitcoin",
  cash: "Tunai",
  value: "Nilai saat itu",
  where: "Disimpan",
  custody: { self: "Kunci sendiri", exchange: "Di bursa", lender: "Di platform pinjaman kripto", etf: "Saham ETF" },
  noPrice: "belum ada harga",
  nodes: {
    mine: {
      head: ["Jan 2009", "Menambang di difficulty 1"],
      default: "Bitcoin v0.1 sudah rilis. Difficulty-nya 1, dan laptop sesekali menemukan blok berisi 50 BTC. Menambang cuma butuh listrik, dan belum ada yang membeli.",
      choices: { month: "Biarkan jalan sebulan penuh", once: "Tambang satu blok iseng, lalu matikan" },
    },
    pizza: {
      head: ["22 Mei 2010", "Laszlo ingin pizza"],
      default: "Di forum, Laszlo baru saja membayar 10.000 BTC untuk dua pizza. Akhirnya bitcoin bisa membeli sesuatu. Kamu ikut membelanjakan sebagian?",
      choices: { spend: "Belanjakan 10% untuk pizza dan game", keep: "Simpan semua koin" },
    },
    parity: {
      head: ["9 Feb 2011", "Satu bitcoin, satu dolar"],
      default: "Bitcoin menyentuh US$1 di Mt. Gox. Setahun lalu harganya cuma pecahan sen. Koinmu mendadak jadi uang sungguhan.",
      choices: { sellHalf: "Jual separuh, kunci untungnya", hold: "Tahan" },
    },
    backup: {
      head: ["Jun 2012", "Di mana wallet.dat-mu?"],
      default: "Koinmu tersimpan dalam satu file di laptop. Forum terus mengingatkan: enkripsi dan backup, atau satu disk rusak menghapus semuanya.",
      choices: { backup: "Enkripsi dan backup ke USB dan kertas", later: "Nanti saja" },
    },
    exchange: {
      head: ["Apr 2013", "Mt. Gox memproses 70% transaksi"],
      default: "Harga naik-turun tajam dan semua aksi ada di Mt. Gox. Menyimpan koin di sana bikin trading gampang. Tapi akhir-akhir ini penarikan sering lambat.",
      choices: { gox: "Simpan koin di Mt. Gox", self: "Pindahkan ke dompet sendiri" },
    },
    laptop: {
      head: ["Nov 2013", "Bitcoin tembus US$1.000"],
      risk: "Bitcoin di atas US$1.000, tapi laptop lamamu mati berbulan-bulan lalu dan kamu tidak pernah membuat backup. Laptopnya ada di kantong dekat pintu bersama barang bekas lain.",
      safe: "Bitcoin di atas US$1.000, naik lebih dari sepuluh kali lipat dalam setahun. Beritanya di mana-mana. Ambil sebagian untung?",
      choices: { trash: "Buang kantongnya", search: "Bongkar dulu disk lamanya", sellHalf: "Jual separuh", hold: "Tahan" },
    },
    gox: {
      head: ["Feb 2014", "Mt. Gox padam"],
      hit: "Penarikan dihentikan 7 Februari. Tanggal 28 Mt. Gox bangkrut dengan sekitar 850.000 BTC hilang, termasuk milikmu. Pengembalian baru dimulai tahun 2024.",
      safe: "Penarikan dihentikan 7 Februari dan Mt. Gox bangkrut tanggal 28, dengan sekitar 850.000 BTC hilang. Koinmu tidak ada di sana.",
      choices: { self: "Mulai sekarang simpan di kunci sendiri", another: "Pakai bursa lain" },
    },
    fork: {
      head: ["1 Agu 2017", "Bitcoin Cash memisahkan diri"],
      has: "Kubu blok besar memisahkan diri sebagai Bitcoin Cash, dan kamu menerima satu BCH untuk tiap BTC yang kamu pegang. Satu BCH setara sekitar 0,127 BTC.",
      none: "Kubu blok besar memisahkan diri sebagai Bitcoin Cash. Karena dompetmu kosong, kamu tidak menerima apa-apa.",
      choices: { swap: "Jual BCH untuk menambah BTC", ignore: "Abaikan", continue: "Lanjut" },
    },
    mania: {
      head: ["17 Des 2017", "Bitcoin dekat US$20.000"],
      default: "Sopir taksi bertanya soal bitcoin. Fee tembus US$50. Sebuah bursa menawarkan leverage 3× dengan sekali klik.",
      choices: { sellHalf: "Jual separuh", hold: "Tahan", leverage: "Pakai leverage 3×" },
    },
    winter: {
      head: ["15 Des 2018", "Musim dingin kripto: −84%"],
      liquidated: "Bulan Februari harga turun sepertiga dan posisi 3×-mu dilikuidasi: semua koin jaminanmu habis. Sekarang bitcoin di sekitar US$3.200.",
      normal: "Setahun setelah puncak, bitcoin di sekitar US$3.200. Berita lagi-lagi menyatakannya mati.",
      choices: { sellAll: "Jual semua", hold: "Tahan", buy: "Beli lagi US$1.000" },
    },
    covid: {
      head: ["12 Mar 2020", "Kamis Hitam"],
      default: "Pandemi menghentikan dunia dan pasar panik. Bitcoin turun sekitar 40% dalam sehari, ke bawah US$5.000.",
      choices: { sellAll: "Jual semua", hold: "Tahan", buy: "Beli lagi US$1.000" },
    },
    yield: {
      head: ["Nov 2021", "Dekat US$69.000 dan bunga 8% setahun"],
      default: "Sebuah platform pinjaman kripto yang mentereng menawarkan bunga 8% untuk bitcoin yang disimpan. Jutaan orang memakainya. Kuncimu cuma diam tanpa hasil.",
      choices: { deposit: "Simpan koin di sana demi 8%", keep: "Tetap pegang kunci sendiri" },
    },
    ftx: {
      head: ["Nov 2022", "Platform pinjaman dan FTX runtuh"],
      hit: "Platformmu membekukan penarikan lalu bangkrut. Klaim dihitung dalam dolar pada tanggal kebangkrutan, jadi bertahun-tahun kemudian kamu menerima uang tunai di harga dasar pasar, bukan koinmu.",
      safe: "Celsius, lalu FTX: satu per satu platform membekukan penarikan. Koinmu tidak ada di satu pun.",
      choices: { self: "Pegang kunci sendiri", exchange: "Tetap pakai bursa" },
    },
    etf: {
      head: ["Jan 2024", "ETF spot hadir"],
      has: "ETF bitcoin spot mulai diperdagangkan. Kamu bisa menukar koinmu dengan saham reksa dana di rekening sekuritas biasa: tanpa kunci, tanpa seed phrase, dengan biaya tahunan kecil.",
      none: "ETF bitcoin spot mulai diperdagangkan di sekitar US$46.000. Masuk lagi?",
      choices: { etf: "Tukar ke saham ETF", keys: "Tetap pegang kunci", buy: "Beli bitcoin US$1.000", skip: "Tidak ikut" },
    },
  },
  result: {
    eyebrow: "Hari ini",
    title: "Ke mana pilihanmu membawa",
    worth: "Nilai dompetmu",
    hodl: "Kalau kamu menahan sejak awal",
    invested: "Uang yang kamu masukkan",
    lost: "Bitcoin yang hilang",
    priceLive: (p) => `Dengan harga live ${p}`,
    priceData: (p, m) => `Dengan ${p}, harga penutupan terakhir di data kami (${m})`,
    journey: "Jalanmu",
    badges: "Pelajaran yang kamu dapat",
    again: "Main lagi",
    other: "Coba titik awal lain",
    toTimeMachine: "Kembali ke Mesin Waktu",
  },
  badges: {
    diamond: ["Diamond hands", "Kamu tidak pernah menjual."],
    pizza: ["Legenda pizza", "Kamu membelanjakan bitcoin sebagai uang, seperti Laszlo."],
    backup: ["Punya backup", "Kuncimu selamat dari laptop yang mati."],
    keys: ["Not your keys, not your coins", "Kamu menutup permainan dengan memegang kunci sendiri."],
    etf: ["Mode gampang", "Saham ETF: tidak ada kunci yang bisa hilang, tapi juga tidak bisa dipakai."],
    fork: ["Selamat dari fork", "Kamu mengubah BCH gratis jadi tambahan bitcoin."],
    trashed: ["Klub TPA", "Seperti James Howells, kamu membuang kuncimu."],
    gox: ["Korban Mt. Gox", "Bursamu memegang koinmu, lalu menghilangkannya."],
    liquidated: ["Terlikuidasi", "Leverage mengubah koreksi jadi bencana."],
    lender: ["Dibekukan", "Platformmu membayar kembali dalam dolar tahun 2022."],
  },
};

export const play = { en, id };
