// Copy for the Time Machine (history page). Moments are keyed by the ids in
// lib/history.js: [date, tag, title, text]. Markup rules match lib/content.js.

const en = {
  eyebrow: "Chapter 01 · Time Machine",
  title: "Travel from <em>2008</em> to today",
  lede: "Scroll, or drag the dial. The window changes with the era: the price, the hashrate, even the software people used. Stop at the orange moments to try history yourself.",
  start: "Start in 2008",
  play: "Play Satoshi's Wallet",
  showAll: (n) => `Show all ${n} moments`,
  showKey: "Key moments only",
  source: "Source",
  tryIt: "Try it",
  eras: {
    genesis: ["Genesis", "2008–2010", "A handful of cypherpunks mine on laptops. Coins have no price yet."],
    experiment: ["Experiment", "2010–2013", "First prices, first exchanges, first scandals."],
    crisis: ["Crisis", "2014–2017", "Mt. Gox falls and the community fights over how to scale."],
    maturity: ["Maturity", "2017–2020", "SegWit, Lightning, a mania and a brutal winter."],
    institutional: ["Institutional", "2021–now", "Companies, countries and ETFs buy in."],
  },
  hardware: { none: "—", cpu: "CPU (laptops)", gpu: "Graphics cards", fpga: "FPGA boards", asic: "First ASICs", farm: "ASIC farms" },
  console: {
    aria: "Bitcoin network at the selected month",
    price: "Price at month end",
    noMarket: "No market yet",
    reference: "reference rate",
    height: "Block height",
    reward: "Block reward",
    mined: "Mined",
    hashrate: "Hashrate",
    tx: "Transactions / day",
    fee: "Avg. fee",
    hardware: "Mining with",
    prelaunch: "Before the first block",
    prelaunchNote: "No blocks, no coins, no price. Only an idea and a domain name.",
    chartAria: "Bitcoin price since July 2010 on a log scale, with the selected month marked",
    idrNote: "Rupiah at that year's average rate",
    // Window titles per skin
    titles: { classic: "Bitcoin v0.1", forum: "Bitcoin Forum", exchange: "BTC/USD · Exchange", mobile: "Wallet", modern: "bitcoin · network" },
    forumNav: ["Home", "Help", "Search", "Profile"],
  },
  dial: {
    label: "Travel through time",
    play: "Play",
    pause: "Pause",
    value: (month, era) => `${month} · ${era}`,
  },
  moments: {
    domain: ["18 Aug 2008", "bitcoin.org", "bitcoin.org is registered", "Two months before the whitepaper, someone anonymously sets the stage."],
    whitepaper: ["31 Oct 2008", "Whitepaper", "\"Bitcoin: A Peer-to-Peer Electronic Cash System\"", "Satoshi Nakamoto sends a nine-page paper to a cryptography mailing list. It solves double-spending without a trusted third party, using proof-of-work and a chain of blocks."],
    genesis: ["3 Jan 2009", "Block #0", "The genesis block is mined", "Its 50 BTC reward can never be spent. The Times headline in its coinbase is both a timestamp and a statement."],
    v01: ["9 Jan 2009", "v0.1", "Bitcoin v0.1 is released", "The first open-source client, for Windows only. Anyone can run a node and mine with an ordinary CPU."],
    hal: ["12 Jan 2009", "Block #170", "First transaction: Satoshi → Hal Finney", "10 BTC changes hands. Finney, who built RPOW, is the first person besides Satoshi to run a node."],
    firstPrice: ["5 Oct 2009", "", "First price: US$1 = 1,309.03 BTC", "New Liberty Standard derives an exchange rate from the cost of the electricity needed to mine one bitcoin."],
    pizza: ["22 May 2010", "Pizza Day", "10,000 BTC for two pizzas", "Laszlo Hanyecz makes the first documented purchase of real goods with bitcoin, worth about $41 at the time."],
    mtgoxOpens: ["18 Jul 2010", "Mt. Gox", "Mt. Gox starts trading bitcoin", "A site built to trade Magic: The Gathering cards becomes a bitcoin exchange. Market prices start here, at about 8 cents."],
    overflow: ["15 Aug 2010", "Block #74,638", "The value overflow incident", "An integer overflow bug creates 184 billion BTC. A patch ships within hours and the chain is forked back, the only major inflation bug ever exploited."],
    satoshiGone: ["12 Dec 2010", "", "Satoshi's last forum post", "Satoshi hands the project to Gavin Andresen and other developers. A last known email follows in April 2011, then silence."],
    parity: ["9 Feb 2011", "$1", "Parity with the dollar", "For the first time, one bitcoin trades for one US dollar on Mt. Gox."],
    silkRoad: ["Feb 2011", "", "Silk Road opens", "A darknet market that only accepts bitcoin brings the first wave of mainstream attention, much of it unwelcome."],
    goxHack: ["19 Jun 2011", "", "Mt. Gox is hacked", "A compromised account dumps coins and the price on Mt. Gox briefly falls from about $17 to one cent. Trading halts for a week."],
    halving1: ["28 Nov 2012", "Halving 1", "Block reward drops 50 → 25 BTC", "Monetary policy written in code runs exactly on schedule at block 210,000."],
    fork2013: ["11 Mar 2013", "BIP 50", "An accidental chain split", "Nodes on v0.8 and v0.7 disagree about one large block and the chain splits. Miners and developers coordinate a return to v0.7's chain within hours."],
    silkRoadDown: ["2 Oct 2013", "", "The FBI shuts down Silk Road", "Its founder is arrested and about 144,000 BTC are later seized. Bitcoin survives its most notorious use."],
    howells: ["2013", "", "8,000 BTC go to the dump", "James Howells, a Welsh IT worker, throws away an old hard drive holding the keys to about 8,000 BTC. Years of pleas to dig up the landfill go nowhere."],
    thousand: ["29 Nov 2013", "$1,000", "Bitcoin passes $1,000", "Demand from China and a friendly US Senate hearing push the price up more than tenfold in a year."],
    goxCollapse: ["Feb 2014", "", "The collapse of Mt. Gox", "The exchange that once handled most of the world's volume halts withdrawals and files for bankruptcy, missing about 850,000 BTC. The lesson keeps repeating: <em>not your keys, not your coins</em>."],
    blocksizeWar: ["Aug 2015", "", "The blocksize war begins", "Bitcoin XT proposes 8 MB blocks. For two years the community argues: scale on-chain with bigger blocks, or keep blocks small and build layers on top?"],
    halving2: ["9 Jul 2016", "Halving 2", "Block reward drops to 12.5 BTC", "Block 420,000. The network matures while the scaling debate heats up."],
    bch: ["1 Aug 2017", "Fork", "Bitcoin Cash splits off", "The big-block camp forks away with 8 MB blocks. Everyone who holds bitcoin receives the same amount of BCH."],
    segwit: ["24 Aug 2017", "SegWit", "Segregated Witness activates", "A soft fork at block 481,824 fixes transaction malleability and paves the way for Lightning."],
    s2x: ["8 Nov 2017", "", "SegWit2x is called off", "The plan to double the block size by hard fork is cancelled. Users running their own nodes, not miners or companies, decide the rules. The blocksize war is over."],
    mania: ["17 Dec 2017", "ATH", "The 2017 mania", "Bitcoin nears $20,000 and CME launches futures. Blocks are full and the average fee tops $50 a transaction for days."],
    lightning: ["15 Mar 2018", "Layer 2", "Lightning Network goes live on mainnet", "Off-chain payment channels for instant, cheap payments, still secured by Bitcoin."],
    winter: ["15 Dec 2018", "−84%", "Crypto winter bottoms out", "A year after the peak, bitcoin trades near $3,200. Most 2017 tokens never recover."],
    covid: ["12 Mar 2020", "Black Thursday", "The pandemic crash", "Markets panic and bitcoin loses about 40% in a day, falling below $5,000."],
    halving3: ["11 May 2020", "Halving 3", "Block reward drops to 6.25 BTC", "Amid pandemic stimulus, the \"digital gold\" narrative takes hold."],
    microstrategy: ["11 Aug 2020", "", "MicroStrategy buys bitcoin", "The software company puts $250 million of its treasury into 21,454 BTC, the start of a buying spree that makes it the largest corporate holder."],
    tesla: ["8 Feb 2021", "", "Tesla buys $1.5 billion", "Corporate treasuries follow. Later that month bitcoin's market value passes $1 trillion."],
    chinaBan: ["Jun 2021", "", "China bans mining", "Around half of the hashrate goes dark within weeks, the biggest drop in Bitcoin's history. Miners move to the US and Kazakhstan, and blocks keep coming."],
    elSalvador: ["7 Sep 2021", "", "El Salvador makes it legal tender", "The first country to adopt bitcoin as official currency, alongside the US dollar."],
    taproot: ["14 Nov 2021", "Taproot", "Taproot &amp; Schnorr signatures", "The biggest upgrade since SegWit, active at block 709,632. BIP 340–342 bring aggregatable signatures and more private scripts. Days earlier, bitcoin peaked near $69,000."],
    terra: ["May 2022", "", "Terra/Luna collapses", "An algorithmic stablecoin unravels and wipes out about $40 billion. Its reserve sells roughly 80,000 BTC trying to defend the peg."],
    ftx: ["11 Nov 2022", "", "FTX files for bankruptcy", "After Celsius and other lenders, one of the largest exchanges falls with customer funds missing. Bitcoin drops below $16,000."],
    ordinals: ["21 Jan 2023", "Ordinals", "Inscriptions arrive", "Ordinals write images and text into individual satoshis using Taproot witness data, and reignite the debate over what blockspace is for."],
    etf: ["10 Jan 2024", "ETF", "SEC approves spot bitcoin ETFs", "Eleven funds begin trading the next day. Bitcoin enters mainstream institutional portfolios."],
    halving4: ["20 Apr 2024", "Halving 4", "Block reward drops to 3.125 BTC", "Block 840,000. More than 93% of the 21 million BTC have been mined."],
    hundredK: ["5 Dec 2024", "$100K", "Bitcoin passes $100,000", "Eleven years after it first crossed $1,000."],
    reserve: ["6 Mar 2025", "", "A US Strategic Bitcoin Reserve", "An executive order creates a reserve funded with bitcoin the government already holds from forfeitures."],
    ath2025: ["6 Oct 2025", "ATH", "A new all-time high", "Bitcoin trades above $126,000. From here on, the story is live."],
  },
  now: {
    eyebrow: "You are here",
    title: "The time machine stops at <em>now</em>",
    lede: "Everything after the last moment is still being written, one block every ten minutes. The window below is live.",
    last: "And after that? Around 2140, after 33 halvings, the last satoshi is mined and miners are paid by fees alone.",
  },
  cta: {
    eyebrow: "Your turn",
    title: "Could you have <em>held on</em>?",
    lede: "Satoshi's Wallet puts you in the same moments with real prices: pizza, Mt. Gox, the fork, the crashes. Every choice has a cost.",
    button: "Play Satoshi's Wallet",
  },
  demos: {
    mine: {
      title: "Mine like it's 2009",
      lede: "In 2009 the difficulty was 1 and a laptop could find a block in hours. Here the target is scaled down so your browser finds one in seconds.",
      start: "Mine a block",
      stop: "Stop",
      searching: (n) => `Hashing… ${n} attempts`,
      found: (n, s) => `Block found after ${n} hashes in ${s} s. +50 BTC`,
      compare: (years) => `At today's network hashrate, this browser would need about ${years} years to find one real block on its own.`,
    },
    send: {
      title: "Send Hal his 10 BTC",
      lede: "The first transaction spends a 50 BTC coinbase from block 9: 10 BTC to Hal, 40 BTC back to Satoshi as change.",
      input: "Input",
      inputValue: "Block 9 coinbase · 50 BTC",
      outputs: "Outputs",
      toHal: "Hal Finney · 10 BTC",
      change: "Satoshi (change) · 40 BTC",
      button: "Sign &amp; broadcast",
      steps: ["Signing with ECDSA on secp256k1…", "Relaying to the only other node on the network…", "Confirmed in block #170. No fee, no bank, no permission."],
      again: "Again",
    },
    pizza: {
      title: "What did those pizzas cost?",
      lede: "The same 10,000 BTC, valued at later moments:",
      paid: "Paid in May 2010",
      nowLive: "Now (live)",
      nowData: (m) => `Latest data (${m})`,
      perPizza: (v) => `${v} per pizza`,
      units: [[1e12, "trillion"], [1e9, "billion"], [1e6, "million"]],
    },
    gox: {
      title: "Withdraw from Mt. Gox",
      lede: "It is early February 2014 and you have 10 BTC on the biggest exchange in the world.",
      button: "Withdraw 10 BTC",
      steps: [
        "Request received. Processing…",
        "Pending. \"Technical issue with transaction malleability.\"",
        "7 Feb 2014: all bitcoin withdrawals halted.",
        "24 Feb: the website goes blank.",
        "28 Feb: bankruptcy. About 850,000 BTC are missing.",
      ],
      lesson: "Repayments only began in 2024, a decade later. Coins on an exchange are a promise from the exchange; coins on your own keys are yours.",
      again: "Reset",
    },
    fees: {
      title: "Get confirmed in December 2017",
      lede: "Blocks are full and hundreds of thousands of transactions are waiting. Pick a fee rate for a typical 226-byte payment.",
      pick: "Fee rate",
      cost: "You pay",
      wait: "Expected wait",
      waits: ["days, maybe never", "about a day", "a few hours", "next block or two"],
      note: "A simplified model of the mempool at the December 2017 peak, priced at $19,250 per BTC.",
    },
    lightning: {
      title: "Pay for a coffee",
      lede: "Same 5,000 sats, two ways. The on-chain lane is sped up 60×.",
      button: "Pay 5,000 sats",
      onchain: "On-chain",
      ln: "Lightning",
      waiting: "Waiting for a block…",
      done: (s) => `Settled in ${s}`,
      took: ["< 1 s", "≈ 10 min"],
      again: "Again",
    },
  },
};

const id = {
  eyebrow: "Bab 01 · Mesin Waktu",
  title: "Berkelana dari <em>2008</em> sampai sekarang",
  lede: "Gulir, atau geser tuas waktunya. Jendelanya ikut berubah sesuai zaman: harga, hashrate, bahkan perangkat lunak yang dipakai orang. Mampir di momen oranye untuk mencoba sejarahnya sendiri.",
  start: "Mulai dari 2008",
  play: "Main Dompet Satoshi",
  showAll: (n) => `Tampilkan semua ${n} momen`,
  showKey: "Momen kunci saja",
  source: "Sumber",
  tryIt: "Coba",
  eras: {
    genesis: ["Genesis", "2008–2010", "Segelintir cypherpunk menambang di laptop. Koinnya belum punya harga."],
    experiment: ["Eksperimen", "2010–2013", "Harga pertama, bursa pertama, skandal pertama."],
    crisis: ["Krisis", "2014–2017", "Mt. Gox runtuh dan komunitas berselisih soal cara menskalakan jaringan."],
    maturity: ["Kematangan", "2017–2020", "SegWit, Lightning, euforia, lalu musim dingin yang brutal."],
    institutional: ["Institusional", "2021–sekarang", "Perusahaan, negara, dan ETF ikut membeli."],
  },
  hardware: { none: "—", cpu: "CPU (laptop)", gpu: "Kartu grafis", fpga: "Papan FPGA", asic: "ASIC pertama", farm: "Ladang ASIC" },
  console: {
    aria: "Jaringan Bitcoin pada bulan yang dipilih",
    price: "Harga akhir bulan",
    noMarket: "Belum ada pasar",
    reference: "kurs acuan",
    height: "Tinggi blok",
    reward: "Imbalan blok",
    mined: "Tertambang",
    hashrate: "Hashrate",
    tx: "Transaksi / hari",
    fee: "Rata-rata fee",
    hardware: "Menambang pakai",
    prelaunch: "Sebelum blok pertama",
    prelaunchNote: "Belum ada blok, koin, maupun harga. Baru sebuah ide dan nama domain.",
    chartAria: "Harga bitcoin sejak Juli 2010 dalam skala log, dengan bulan yang dipilih ditandai",
    idrNote: "Rupiah dengan kurs rata-rata tahun itu",
    titles: { classic: "Bitcoin v0.1", forum: "Bitcoin Forum", exchange: "BTC/USD · Bursa", mobile: "Dompet", modern: "bitcoin · jaringan" },
    forumNav: ["Beranda", "Bantuan", "Cari", "Profil"],
  },
  dial: {
    label: "Berkelana menembus waktu",
    play: "Putar",
    pause: "Jeda",
    value: (month, era) => `${month} · ${era}`,
  },
  moments: {
    domain: ["18 Agu 2008", "bitcoin.org", "Domain bitcoin.org didaftarkan", "Dua bulan sebelum whitepaper beredar, panggungnya sudah disiapkan secara anonim."],
    whitepaper: ["31 Okt 2008", "Whitepaper", "\"Bitcoin: A Peer-to-Peer Electronic Cash System\"", "Satoshi Nakamoto mengirim makalah sembilan halaman ke milis kriptografi. Isinya menjawab masalah double-spend tanpa pihak ketiga, dengan proof-of-work dan rantai blok."],
    genesis: ["3 Jan 2009", "Blok #0", "Blok genesis ditambang", "Imbalan 50 BTC-nya tidak akan pernah bisa dibelanjakan. Judul koran The Times di coinbase-nya jadi stempel waktu sekaligus pernyataan sikap."],
    v01: ["9 Jan 2009", "v0.1", "Bitcoin v0.1 dirilis", "Klien open source pertama, khusus Windows. Siapa pun bisa menjalankan node dan menambang dengan CPU biasa."],
    hal: ["12 Jan 2009", "Blok #170", "Transaksi pertama: Satoshi → Hal Finney", "10 BTC berpindah tangan. Finney, pembuat RPOW, menjadi orang pertama selain Satoshi yang menjalankan node."],
    firstPrice: ["5 Okt 2009", "", "Harga pertama: US$1 = 1.309,03 BTC", "New Liberty Standard menghitung kurs dari biaya listrik untuk menambang satu bitcoin."],
    pizza: ["22 Mei 2010", "Pizza Day", "10.000 BTC untuk dua pizza", "Laszlo Hanyecz melakukan pembelian barang nyata pertama yang terdokumentasi dengan bitcoin, senilai sekitar US$41 waktu itu."],
    mtgoxOpens: ["18 Jul 2010", "Mt. Gox", "Mt. Gox mulai memperdagangkan bitcoin", "Situs yang awalnya untuk jual-beli kartu Magic: The Gathering berubah jadi bursa bitcoin. Harga pasar dimulai di sini, sekitar 8 sen."],
    overflow: ["15 Agu 2010", "Blok #74.638", "Insiden value overflow", "Bug integer overflow menciptakan 184 miliar BTC. Dalam beberapa jam patch dirilis dan rantai di-fork kembali. Ini satu-satunya bug inflasi besar yang pernah dieksploitasi."],
    satoshiGone: ["12 Des 2010", "", "Postingan forum terakhir Satoshi", "Satoshi menyerahkan proyek ke Gavin Andresen dan pengembang lain. Email terakhir yang diketahui menyusul April 2011, lalu sunyi."],
    parity: ["9 Feb 2011", "$1", "Setara dengan dolar", "Untuk pertama kalinya, satu bitcoin diperdagangkan seharga satu dolar AS di Mt. Gox."],
    silkRoad: ["Feb 2011", "", "Silk Road dibuka", "Pasar darknet yang hanya menerima bitcoin membawa gelombang perhatian publik pertama, sebagian besar tidak diharapkan."],
    goxHack: ["19 Jun 2011", "", "Mt. Gox diretas", "Akun yang dibobol membuang koin dan harga di Mt. Gox sempat jatuh dari sekitar US$17 ke satu sen. Perdagangan berhenti seminggu."],
    halving1: ["28 Nov 2012", "Halving 1", "Imbalan blok turun 50 → 25 BTC", "Kebijakan moneter yang tertulis di kode berjalan persis sesuai jadwal di blok 210.000."],
    fork2013: ["11 Mar 2013", "BIP 50", "Rantai terbelah tanpa sengaja", "Node v0.8 dan v0.7 berbeda pendapat soal satu blok besar sehingga rantai terbelah. Penambang dan pengembang berkoordinasi kembali ke rantai v0.7 dalam hitungan jam."],
    silkRoadDown: ["2 Okt 2013", "", "FBI menutup Silk Road", "Pendirinya ditangkap dan sekitar 144.000 BTC kemudian disita. Bitcoin selamat dari penggunaannya yang paling terkenal buruk."],
    howells: ["2013", "", "8.000 BTC dibuang ke TPA", "James Howells, pekerja IT asal Wales, membuang hard disk lama berisi kunci sekitar 8.000 BTC. Permohonannya bertahun-tahun untuk menggali TPA tidak pernah dikabulkan."],
    thousand: ["29 Nov 2013", "$1.000", "Bitcoin tembus US$1.000", "Permintaan dari China dan sidang Senat AS yang bersahabat mendorong harga naik lebih dari sepuluh kali lipat dalam setahun."],
    goxCollapse: ["Feb 2014", "", "Runtuhnya Mt. Gox", "Bursa yang pernah memproses sebagian besar volume dunia menghentikan penarikan dan bangkrut, dengan sekitar 850.000 BTC hilang. Pelajaran yang terus berulang: <em>not your keys, not your coins</em>."],
    blocksizeWar: ["Agu 2015", "", "Perang ukuran blok dimulai", "Bitcoin XT mengusulkan blok 8 MB. Dua tahun komunitas berdebat: menskalakan on-chain dengan blok lebih besar, atau menjaga blok tetap kecil dan membangun lapisan di atasnya?"],
    halving2: ["9 Jul 2016", "Halving 2", "Imbalan blok turun ke 12,5 BTC", "Blok 420.000. Jaringan makin matang sementara debat skalabilitas memanas."],
    bch: ["1 Agu 2017", "Fork", "Bitcoin Cash memisahkan diri", "Kubu blok besar memisahkan diri dengan blok 8 MB. Semua pemegang bitcoin menerima BCH dalam jumlah yang sama."],
    segwit: ["24 Agu 2017", "SegWit", "Segregated Witness aktif", "Soft fork di blok 481.824 memperbaiki malleability transaksi dan membuka jalan bagi Lightning."],
    s2x: ["8 Nov 2017", "", "SegWit2x dibatalkan", "Rencana menggandakan ukuran blok lewat hard fork batal. Pengguna yang menjalankan node sendiri, bukan penambang atau perusahaan, yang menentukan aturan. Perang ukuran blok selesai."],
    mania: ["17 Des 2017", "ATH", "Euforia 2017", "Bitcoin mendekati US$20.000 dan CME meluncurkan futures. Blok penuh dan rata-rata fee lebih dari US$50 per transaksi selama berhari-hari."],
    lightning: ["15 Mar 2018", "Layer 2", "Lightning Network di mainnet", "Kanal pembayaran off-chain untuk transaksi instan dan murah, tetap dijamin oleh Bitcoin."],
    winter: ["15 Des 2018", "−84%", "Dasar musim dingin kripto", "Setahun setelah puncak, bitcoin di sekitar US$3.200. Sebagian besar token 2017 tidak pernah pulih."],
    covid: ["12 Mar 2020", "Kamis Hitam", "Crash pandemi", "Pasar panik dan bitcoin turun sekitar 40% dalam sehari, ke bawah US$5.000."],
    halving3: ["11 Mei 2020", "Halving 3", "Imbalan blok turun ke 6,25 BTC", "Di tengah stimulus pandemi, narasi \"emas digital\" makin menguat."],
    microstrategy: ["11 Agu 2020", "", "MicroStrategy membeli bitcoin", "Perusahaan perangkat lunak ini menaruh US$250 juta kasnya ke 21.454 BTC, awal dari pembelian beruntun yang menjadikannya pemegang korporat terbesar."],
    tesla: ["8 Feb 2021", "", "Tesla membeli US$1,5 miliar", "Kas perusahaan ikut masuk. Akhir bulan itu nilai pasar bitcoin melewati US$1 triliun."],
    chinaBan: ["Jun 2021", "", "China melarang mining", "Sekitar separuh hashrate padam dalam beberapa minggu, penurunan terbesar dalam sejarah Bitcoin. Penambang pindah ke AS dan Kazakhstan, dan blok tetap terus muncul."],
    elSalvador: ["7 Sep 2021", "", "El Salvador: alat pembayaran sah", "Negara pertama yang menjadikan bitcoin mata uang resmi, di samping dolar AS."],
    taproot: ["14 Nov 2021", "Taproot", "Taproot &amp; tanda tangan Schnorr", "Upgrade terbesar sejak SegWit, aktif di blok 709.632. BIP 340–342 membawa tanda tangan yang bisa diagregasi dan skrip yang lebih privat. Beberapa hari sebelumnya bitcoin memuncak di dekat US$69.000."],
    terra: ["Mei 2022", "", "Terra/Luna runtuh", "Stablecoin algoritmik ambruk dan menghapus sekitar US$40 miliar. Cadangannya menjual kira-kira 80.000 BTC untuk mempertahankan patokan harga."],
    ftx: ["11 Nov 2022", "", "FTX bangkrut", "Setelah Celsius dan pemberi pinjaman lain, salah satu bursa terbesar ikut tumbang dengan dana nasabah raib. Bitcoin jatuh ke bawah US$16.000."],
    ordinals: ["21 Jan 2023", "Ordinals", "Inscription hadir", "Ordinals menulis gambar dan teks ke satoshi tertentu memakai data witness Taproot, dan memanaskan lagi debat soal untuk apa ruang blok dipakai."],
    etf: ["10 Jan 2024", "ETF", "SEC menyetujui ETF bitcoin spot", "Sebelas dana mulai diperdagangkan keesokan harinya. Bitcoin resmi masuk portofolio institusi arus utama."],
    halving4: ["20 Apr 2024", "Halving 4", "Imbalan blok turun ke 3,125 BTC", "Blok 840.000. Lebih dari 93% dari 21 juta BTC sudah ditambang."],
    hundredK: ["5 Des 2024", "$100K", "Bitcoin tembus US$100.000", "Sebelas tahun setelah pertama kali melewati US$1.000."],
    reserve: ["6 Mar 2025", "", "Cadangan Bitcoin Strategis AS", "Perintah eksekutif membentuk cadangan dari bitcoin yang sudah dimiliki pemerintah hasil penyitaan."],
    ath2025: ["6 Okt 2025", "ATH", "Rekor tertinggi baru", "Bitcoin diperdagangkan di atas US$126.000. Dari sini, ceritanya berlangsung live."],
  },
  now: {
    eyebrow: "Kamu di sini",
    title: "Mesin waktu berhenti di <em>sekarang</em>",
    lede: "Semua setelah momen terakhir masih sedang ditulis, satu blok tiap sepuluh menit. Jendela di bawah ini live.",
    last: "Lalu setelahnya? Sekitar 2140, setelah 33 halving, satoshi terakhir ditambang dan penambang hanya dibayar dari fee.",
  },
  cta: {
    eyebrow: "Giliranmu",
    title: "Sanggupkah kamu <em>bertahan</em>?",
    lede: "Dompet Satoshi menaruhmu di momen yang sama dengan harga sungguhan: pizza, Mt. Gox, fork, dan crash. Setiap pilihan ada harganya.",
    button: "Main Dompet Satoshi",
  },
  demos: {
    mine: {
      title: "Menambang ala 2009",
      lede: "Tahun 2009 difficulty-nya 1 dan laptop bisa menemukan blok dalam hitungan jam. Di sini target diperkecil supaya browsermu menemukannya dalam hitungan detik.",
      start: "Tambang satu blok",
      stop: "Berhenti",
      searching: (n) => `Menghitung hash… ${n} percobaan`,
      found: (n, s) => `Blok ditemukan setelah ${n} hash dalam ${s} detik. +50 BTC`,
      compare: (years) => `Dengan hashrate jaringan hari ini, browser ini butuh sekitar ${years} tahun untuk menemukan satu blok sungguhan sendirian.`,
    },
    send: {
      title: "Kirim 10 BTC ke Hal",
      lede: "Transaksi pertama membelanjakan coinbase 50 BTC dari blok 9: 10 BTC untuk Hal, 40 BTC kembali ke Satoshi sebagai kembalian.",
      input: "Input",
      inputValue: "Coinbase blok 9 · 50 BTC",
      outputs: "Output",
      toHal: "Hal Finney · 10 BTC",
      change: "Satoshi (kembalian) · 40 BTC",
      button: "Tanda tangani &amp; siarkan",
      steps: ["Menandatangani dengan ECDSA di secp256k1…", "Meneruskan ke satu-satunya node lain di jaringan…", "Terkonfirmasi di blok #170. Tanpa fee, tanpa bank, tanpa izin."],
      again: "Ulangi",
    },
    pizza: {
      title: "Berapa harga pizza itu sebenarnya?",
      lede: "10.000 BTC yang sama, dinilai di momen-momen berikutnya:",
      paid: "Dibayar Mei 2010",
      nowLive: "Sekarang (live)",
      nowData: (m) => `Data terakhir (${m})`,
      perPizza: (v) => `${v} per pizza`,
      units: [[1e12, "triliun"], [1e9, "miliar"], [1e6, "juta"]],
    },
    gox: {
      title: "Tarik dana dari Mt. Gox",
      lede: "Awal Februari 2014, kamu punya 10 BTC di bursa terbesar di dunia.",
      button: "Tarik 10 BTC",
      steps: [
        "Permintaan diterima. Diproses…",
        "Tertunda. \"Masalah teknis terkait transaction malleability.\"",
        "7 Feb 2014: semua penarikan bitcoin dihentikan.",
        "24 Feb: situsnya kosong.",
        "28 Feb: bangkrut. Sekitar 850.000 BTC hilang.",
      ],
      lesson: "Pengembalian dana baru dimulai 2024, satu dekade kemudian. Koin di bursa hanyalah janji dari bursa; koin di kuncimu sendiri benar-benar milikmu.",
      again: "Ulang",
    },
    fees: {
      title: "Terkonfirmasi di Desember 2017",
      lede: "Blok penuh dan ratusan ribu transaksi mengantre. Pilih fee rate untuk pembayaran biasa berukuran 226 byte.",
      pick: "Fee rate",
      cost: "Kamu bayar",
      wait: "Perkiraan tunggu",
      waits: ["berhari-hari, mungkin tak pernah", "sekitar sehari", "beberapa jam", "satu-dua blok berikutnya"],
      note: "Model sederhana mempool di puncak Desember 2017, dengan harga US$19.250 per BTC.",
    },
    lightning: {
      title: "Bayar kopi",
      lede: "5.000 sats yang sama, dua cara. Jalur on-chain dipercepat 60×.",
      button: "Bayar 5.000 sats",
      onchain: "On-chain",
      ln: "Lightning",
      waiting: "Menunggu blok…",
      done: (s) => `Lunas dalam ${s}`,
      took: ["< 1 detik", "≈ 10 menit"],
      again: "Ulangi",
    },
  },
};

export const tm = { en, id };
