// Reference catalog; descriptions per language live in content.sources.desc.
export const SOURCES = {
  whitepaper: ["Bitcoin Whitepaper", "https://bitcoin.org/bitcoin.pdf"],
  nakamoto: ["Satoshi Nakamoto Institute", "https://nakamotoinstitute.org/"],
  core: ["bitcoin/bitcoin", "https://github.com/bitcoin/bitcoin"],
  bips: ["bitcoin/bips", "https://github.com/bitcoin/bips"],
  secp: ["bitcoin-core/secp256k1", "https://github.com/bitcoin-core/secp256k1"],
  bitcoinbook: ["bitcoinbook/bitcoinbook", "https://github.com/bitcoinbook/bitcoinbook"],
  bolts: ["lightning/bolts", "https://github.com/lightning/bolts"],
  mempool: ["mempool/mempool", "https://github.com/mempool/mempool"],
  devdocs: ["Bitcoin Developer Docs", "https://developer.bitcoin.org/"],
  lmab: ["Learn Me A Bitcoin", "https://learnmeabitcoin.com/"],
  fips: ["NIST FIPS 180-4", "https://csrc.nist.gov/pubs/fips/180-4/upd1/final"],
  sec2: ["SEC 2: Recommended Elliptic Curve Domain Parameters", "https://www.secg.org/sec2-v2.pdf"],
  dogecoin: ["dogecoin/dogecoin", "https://github.com/dogecoin/dogecoin"],
  univ2: ["Uniswap/v2-core", "https://github.com/Uniswap/v2-core"],
  uniwp: ["Uniswap v2 Whitepaper", "https://app.uniswap.org/whitepaper.pdf"],
  raydium: ["raydium-io/raydium-amm", "https://github.com/raydium-io/raydium-amm"],
  spltoken: ["Solana SPL Token", "https://spl.solana.com/token"],
  shibburn: ["CoinDesk · SHIB burn", "https://www.coindesk.com/markets/2021/05/17/vitalik-buterin-burns-6b-in-shib-tokens-says-he-doesnt-want-the-power"],
  safemoon: ["CoinDesk · SafeMoon charges", "https://www.coindesk.com/policy/2023/11/01/sec-charges-safemoon-team-with-fraud-offering-unregistered-crypto-securities"],
  binancewif: ["Binance · WIF listing", "https://www.binance.com/en/support/announcement/binance-will-list-dogwifhat-wif-with-seed-tag-applied-90ad67fe5be7483ea058191bfde677e4"],
};
