// Reference catalog; descriptions per language live in content.sources.desc.
export const SOURCES = {
  whitepaper: ["Bitcoin Whitepaper", "https://bitcoin.org/bitcoin.pdf"],
  nakamoto: ["Satoshi Nakamoto Institute", "https://nakamotoinstitute.org/"],
  core: ["bitcoin/bitcoin", "https://github.com/bitcoin/bitcoin"],
  bips: ["bitcoin/bips", "https://github.com/bitcoin/bips"],
  secp: ["bitcoin-core/secp256k1", "https://github.com/bitcoin-core/secp256k1"],
  bitcoinbook: ["bitcoinbook/bitcoinbook", "https://github.com/bitcoinbook/bitcoinbook"],
  bolts: ["lightning/bolts", "https://github.com/lightning/bolts"],
  mempool: ["mempool/mempool", "https://github.com/mempool/mempool"],
  devdocs: ["Bitcoin Developer Docs", "https://developer.bitcoin.org/"],
  lmab: ["Learn Me A Bitcoin", "https://learnmeabitcoin.com/"],
  fips: ["NIST FIPS 180-4", "https://csrc.nist.gov/pubs/fips/180-4/upd1/final"],
  sec2: ["SEC 2: Recommended Elliptic Curve Domain Parameters", "https://www.secg.org/sec2-v2.pdf"],
  dogecoin: ["dogecoin/dogecoin", "https://github.com/dogecoin/dogecoin"],
  brc20: ["BRC-20 experiment (Domo)", "https://domo-2.gitbook.io/brc-20-experiment/"],
  runes: ["Ordinals handbook · Runes", "https://docs.ordinals.com/runes.html"],
  goat: ["Cointelegraph · GOAT and Truth Terminal", "https://cointelegraph.com/news/ai-bot-didnt-launch-goat-memecoin-did-promote-it"],
  pumpsale: ["The Block · PUMP token sale", "https://theblock.co/post/362320/pump-fun-raises-500-million-in-12-minutes-as-pump-tokens-fully-sell-out"],
  doje: ["CF Benchmarks · DOJE launch", "https://www.cfbenchmarks.com/blog/rex-osprey-launches-rex-osprey-doge-etf-doje-first-us-dogecoin-etf"],
  univ2: ["Uniswap/v2-core", "https://github.com/Uniswap/v2-core"],
  uniwp: ["Uniswap v2 Whitepaper", "https://app.uniswap.org/whitepaper.pdf"],
  raydium: ["raydium-io/raydium-amm", "https://github.com/raydium-io/raydium-amm"],
  spltoken: ["Solana SPL Token", "https://spl.solana.com/token"],
  shibburn: ["CoinDesk · SHIB burn", "https://www.coindesk.com/markets/2021/05/17/vitalik-buterin-burns-6b-in-shib-tokens-says-he-doesnt-want-the-power"],
  safemoon: ["CoinDesk · SafeMoon charges", "https://www.coindesk.com/policy/2023/11/01/sec-charges-safemoon-team-with-fraud-offering-unregistered-crypto-securities"],
  binancewif: ["Binance · WIF listing", "https://www.binance.com/en/support/announcement/binance-will-list-dogwifhat-wif-with-seed-tag-applied-90ad67fe5be7483ea058191bfde677e4"],
  coinmetrics: ["coinmetrics/data", "https://github.com/coinmetrics/data"],
  btcwiki: ["Bitcoin Wiki · History", "https://en.bitcoin.it/wiki/History"],
  block170: ["mempool.space · Block 170", "https://mempool.space/block/00000000d1145790a8694403d4063f323d499e655c83426834d4ce2f8dd4a2ee"],
  pizza: ["BitcoinTalk · Pizza for bitcoins?", "https://bitcointalk.org/index.php?topic=137.0"],
  mtgox: ["Wikipedia · Mt. Gox", "https://en.wikipedia.org/wiki/Mt._Gox"],
  overflow: ["Bitcoin Wiki · Value overflow incident", "https://en.bitcoin.it/wiki/Value_overflow_incident"],
  bip50: ["BIP 50", "https://github.com/bitcoin/bips/blob/master/bip-0050.mediawiki"],
  bip141: ["BIP 141", "https://github.com/bitcoin/bips/blob/master/bip-0141.mediawiki"],
  bip341: ["BIP 341", "https://github.com/bitcoin/bips/blob/master/bip-0341.mediawiki"],
  elsalvador: ["Wikipedia · Bitcoin in El Salvador", "https://en.wikipedia.org/wiki/Bitcoin_in_El_Salvador"],
  ftx: ["Wikipedia · Bankruptcy of FTX", "https://en.wikipedia.org/wiki/Bankruptcy_of_FTX"],
  ord: ["ordinals/ord", "https://github.com/ordinals/ord"],
  secetf: ["SEC · Statement on spot bitcoin ETPs", "https://www.sec.gov/news/statement/gensler-statement-spot-bitcoin-011023"],
  reserve: ["White House · Strategic Bitcoin Reserve", "https://www.whitehouse.gov/presidential-actions/2025/03/establishment-of-the-strategic-bitcoin-reserve-and-united-states-digital-asset-stockpile/"],
};
